// Code generated by ent, DO NOT EDIT.

package providerquotastatus

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldDeletedAt, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldChannelID, v))
}

// ScopeKey applies equality check predicate on the "scope_key" field. It's identical to ScopeKeyEQ.
func ScopeKey(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldScopeKey, v))
}

// CredentialID applies equality check predicate on the "credential_id" field. It's identical to CredentialIDEQ.
func CredentialID(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialFingerprint applies equality check predicate on the "credential_fingerprint" field. It's identical to CredentialFingerprintEQ.
func CredentialFingerprint(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldCredentialFingerprint, v))
}

// SecretFingerprint applies equality check predicate on the "secret_fingerprint" field. It's identical to SecretFingerprintEQ.
func SecretFingerprint(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldSecretFingerprint, v))
}

// ResourceScopeKey applies equality check predicate on the "resource_scope_key" field. It's identical to ResourceScopeKeyEQ.
func ResourceScopeKey(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldResourceScopeKey, v))
}

// QuotaScopeID applies equality check predicate on the "quota_scope_id" field. It's identical to QuotaScopeIDEQ.
func QuotaScopeID(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldQuotaScopeID, v))
}

// NextResetAt applies equality check predicate on the "next_reset_at" field. It's identical to NextResetAtEQ.
func NextResetAt(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldNextResetAt, v))
}

// Ready applies equality check predicate on the "ready" field. It's identical to ReadyEQ.
func Ready(v bool) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldReady, v))
}

// NextCheckAt applies equality check predicate on the "next_check_at" field. It's identical to NextCheckAtEQ.
func NextCheckAt(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldNextCheckAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldDeletedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotNull(FieldChannelID))
}

// ScopeKeyEQ applies the EQ predicate on the "scope_key" field.
func ScopeKeyEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldScopeKey, v))
}

// ScopeKeyNEQ applies the NEQ predicate on the "scope_key" field.
func ScopeKeyNEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldScopeKey, v))
}

// ScopeKeyIn applies the In predicate on the "scope_key" field.
func ScopeKeyIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldScopeKey, vs...))
}

// ScopeKeyNotIn applies the NotIn predicate on the "scope_key" field.
func ScopeKeyNotIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldScopeKey, vs...))
}

// ScopeKeyGT applies the GT predicate on the "scope_key" field.
func ScopeKeyGT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldScopeKey, v))
}

// ScopeKeyGTE applies the GTE predicate on the "scope_key" field.
func ScopeKeyGTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldScopeKey, v))
}

// ScopeKeyLT applies the LT predicate on the "scope_key" field.
func ScopeKeyLT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldScopeKey, v))
}

// ScopeKeyLTE applies the LTE predicate on the "scope_key" field.
func ScopeKeyLTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldScopeKey, v))
}

// ScopeKeyContains applies the Contains predicate on the "scope_key" field.
func ScopeKeyContains(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContains(FieldScopeKey, v))
}

// ScopeKeyHasPrefix applies the HasPrefix predicate on the "scope_key" field.
func ScopeKeyHasPrefix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasPrefix(FieldScopeKey, v))
}

// ScopeKeyHasSuffix applies the HasSuffix predicate on the "scope_key" field.
func ScopeKeyHasSuffix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasSuffix(FieldScopeKey, v))
}

// ScopeKeyEqualFold applies the EqualFold predicate on the "scope_key" field.
func ScopeKeyEqualFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEqualFold(FieldScopeKey, v))
}

// ScopeKeyContainsFold applies the ContainsFold predicate on the "scope_key" field.
func ScopeKeyContainsFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContainsFold(FieldScopeKey, v))
}

// CredentialIDEQ applies the EQ predicate on the "credential_id" field.
func CredentialIDEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credential_id" field.
func CredentialIDNEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credential_id" field.
func CredentialIDIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credential_id" field.
func CredentialIDNotIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDIsNil applies the IsNil predicate on the "credential_id" field.
func CredentialIDIsNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIsNull(FieldCredentialID))
}

// CredentialIDNotNil applies the NotNil predicate on the "credential_id" field.
func CredentialIDNotNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotNull(FieldCredentialID))
}

// CredentialFingerprintEQ applies the EQ predicate on the "credential_fingerprint" field.
func CredentialFingerprintEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldCredentialFingerprint, v))
}

// CredentialFingerprintNEQ applies the NEQ predicate on the "credential_fingerprint" field.
func CredentialFingerprintNEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldCredentialFingerprint, v))
}

// CredentialFingerprintIn applies the In predicate on the "credential_fingerprint" field.
func CredentialFingerprintIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldCredentialFingerprint, vs...))
}

// CredentialFingerprintNotIn applies the NotIn predicate on the "credential_fingerprint" field.
func CredentialFingerprintNotIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldCredentialFingerprint, vs...))
}

// CredentialFingerprintGT applies the GT predicate on the "credential_fingerprint" field.
func CredentialFingerprintGT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldCredentialFingerprint, v))
}

// CredentialFingerprintGTE applies the GTE predicate on the "credential_fingerprint" field.
func CredentialFingerprintGTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldCredentialFingerprint, v))
}

// CredentialFingerprintLT applies the LT predicate on the "credential_fingerprint" field.
func CredentialFingerprintLT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldCredentialFingerprint, v))
}

// CredentialFingerprintLTE applies the LTE predicate on the "credential_fingerprint" field.
func CredentialFingerprintLTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldCredentialFingerprint, v))
}

// CredentialFingerprintContains applies the Contains predicate on the "credential_fingerprint" field.
func CredentialFingerprintContains(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContains(FieldCredentialFingerprint, v))
}

// CredentialFingerprintHasPrefix applies the HasPrefix predicate on the "credential_fingerprint" field.
func CredentialFingerprintHasPrefix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasPrefix(FieldCredentialFingerprint, v))
}

// CredentialFingerprintHasSuffix applies the HasSuffix predicate on the "credential_fingerprint" field.
func CredentialFingerprintHasSuffix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasSuffix(FieldCredentialFingerprint, v))
}

// CredentialFingerprintIsNil applies the IsNil predicate on the "credential_fingerprint" field.
func CredentialFingerprintIsNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIsNull(FieldCredentialFingerprint))
}

// CredentialFingerprintNotNil applies the NotNil predicate on the "credential_fingerprint" field.
func CredentialFingerprintNotNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotNull(FieldCredentialFingerprint))
}

// CredentialFingerprintEqualFold applies the EqualFold predicate on the "credential_fingerprint" field.
func CredentialFingerprintEqualFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEqualFold(FieldCredentialFingerprint, v))
}

// CredentialFingerprintContainsFold applies the ContainsFold predicate on the "credential_fingerprint" field.
func CredentialFingerprintContainsFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContainsFold(FieldCredentialFingerprint, v))
}

// SecretFingerprintEQ applies the EQ predicate on the "secret_fingerprint" field.
func SecretFingerprintEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldSecretFingerprint, v))
}

// SecretFingerprintNEQ applies the NEQ predicate on the "secret_fingerprint" field.
func SecretFingerprintNEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldSecretFingerprint, v))
}

// SecretFingerprintIn applies the In predicate on the "secret_fingerprint" field.
func SecretFingerprintIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldSecretFingerprint, vs...))
}

// SecretFingerprintNotIn applies the NotIn predicate on the "secret_fingerprint" field.
func SecretFingerprintNotIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldSecretFingerprint, vs...))
}

// SecretFingerprintGT applies the GT predicate on the "secret_fingerprint" field.
func SecretFingerprintGT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldSecretFingerprint, v))
}

// SecretFingerprintGTE applies the GTE predicate on the "secret_fingerprint" field.
func SecretFingerprintGTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldSecretFingerprint, v))
}

// SecretFingerprintLT applies the LT predicate on the "secret_fingerprint" field.
func SecretFingerprintLT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldSecretFingerprint, v))
}

// SecretFingerprintLTE applies the LTE predicate on the "secret_fingerprint" field.
func SecretFingerprintLTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldSecretFingerprint, v))
}

// SecretFingerprintContains applies the Contains predicate on the "secret_fingerprint" field.
func SecretFingerprintContains(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContains(FieldSecretFingerprint, v))
}

// SecretFingerprintHasPrefix applies the HasPrefix predicate on the "secret_fingerprint" field.
func SecretFingerprintHasPrefix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasPrefix(FieldSecretFingerprint, v))
}

// SecretFingerprintHasSuffix applies the HasSuffix predicate on the "secret_fingerprint" field.
func SecretFingerprintHasSuffix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasSuffix(FieldSecretFingerprint, v))
}

// SecretFingerprintIsNil applies the IsNil predicate on the "secret_fingerprint" field.
func SecretFingerprintIsNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIsNull(FieldSecretFingerprint))
}

// SecretFingerprintNotNil applies the NotNil predicate on the "secret_fingerprint" field.
func SecretFingerprintNotNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotNull(FieldSecretFingerprint))
}

// SecretFingerprintEqualFold applies the EqualFold predicate on the "secret_fingerprint" field.
func SecretFingerprintEqualFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEqualFold(FieldSecretFingerprint, v))
}

// SecretFingerprintContainsFold applies the ContainsFold predicate on the "secret_fingerprint" field.
func SecretFingerprintContainsFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContainsFold(FieldSecretFingerprint, v))
}

// ResourceScopeKeyEQ applies the EQ predicate on the "resource_scope_key" field.
func ResourceScopeKeyEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldResourceScopeKey, v))
}

// ResourceScopeKeyNEQ applies the NEQ predicate on the "resource_scope_key" field.
func ResourceScopeKeyNEQ(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldResourceScopeKey, v))
}

// ResourceScopeKeyIn applies the In predicate on the "resource_scope_key" field.
func ResourceScopeKeyIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldResourceScopeKey, vs...))
}

// ResourceScopeKeyNotIn applies the NotIn predicate on the "resource_scope_key" field.
func ResourceScopeKeyNotIn(vs ...string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldResourceScopeKey, vs...))
}

// ResourceScopeKeyGT applies the GT predicate on the "resource_scope_key" field.
func ResourceScopeKeyGT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldResourceScopeKey, v))
}

// ResourceScopeKeyGTE applies the GTE predicate on the "resource_scope_key" field.
func ResourceScopeKeyGTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldResourceScopeKey, v))
}

// ResourceScopeKeyLT applies the LT predicate on the "resource_scope_key" field.
func ResourceScopeKeyLT(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldResourceScopeKey, v))
}

// ResourceScopeKeyLTE applies the LTE predicate on the "resource_scope_key" field.
func ResourceScopeKeyLTE(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldResourceScopeKey, v))
}

// ResourceScopeKeyContains applies the Contains predicate on the "resource_scope_key" field.
func ResourceScopeKeyContains(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContains(FieldResourceScopeKey, v))
}

// ResourceScopeKeyHasPrefix applies the HasPrefix predicate on the "resource_scope_key" field.
func ResourceScopeKeyHasPrefix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasPrefix(FieldResourceScopeKey, v))
}

// ResourceScopeKeyHasSuffix applies the HasSuffix predicate on the "resource_scope_key" field.
func ResourceScopeKeyHasSuffix(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldHasSuffix(FieldResourceScopeKey, v))
}

// ResourceScopeKeyIsNil applies the IsNil predicate on the "resource_scope_key" field.
func ResourceScopeKeyIsNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIsNull(FieldResourceScopeKey))
}

// ResourceScopeKeyNotNil applies the NotNil predicate on the "resource_scope_key" field.
func ResourceScopeKeyNotNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotNull(FieldResourceScopeKey))
}

// ResourceScopeKeyEqualFold applies the EqualFold predicate on the "resource_scope_key" field.
func ResourceScopeKeyEqualFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEqualFold(FieldResourceScopeKey, v))
}

// ResourceScopeKeyContainsFold applies the ContainsFold predicate on the "resource_scope_key" field.
func ResourceScopeKeyContainsFold(v string) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldContainsFold(FieldResourceScopeKey, v))
}

// QuotaScopeIDEQ applies the EQ predicate on the "quota_scope_id" field.
func QuotaScopeIDEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldQuotaScopeID, v))
}

// QuotaScopeIDNEQ applies the NEQ predicate on the "quota_scope_id" field.
func QuotaScopeIDNEQ(v int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldQuotaScopeID, v))
}

// QuotaScopeIDIn applies the In predicate on the "quota_scope_id" field.
func QuotaScopeIDIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldQuotaScopeID, vs...))
}

// QuotaScopeIDNotIn applies the NotIn predicate on the "quota_scope_id" field.
func QuotaScopeIDNotIn(vs ...int) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldQuotaScopeID, vs...))
}

// QuotaScopeIDIsNil applies the IsNil predicate on the "quota_scope_id" field.
func QuotaScopeIDIsNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIsNull(FieldQuotaScopeID))
}

// QuotaScopeIDNotNil applies the NotNil predicate on the "quota_scope_id" field.
func QuotaScopeIDNotNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotNull(FieldQuotaScopeID))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v ProviderType) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldProviderType, v))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v ProviderType) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldProviderType, v))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...ProviderType) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldProviderType, vs...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...ProviderType) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldProviderType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldStatus, vs...))
}

// NextResetAtEQ applies the EQ predicate on the "next_reset_at" field.
func NextResetAtEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldNextResetAt, v))
}

// NextResetAtNEQ applies the NEQ predicate on the "next_reset_at" field.
func NextResetAtNEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldNextResetAt, v))
}

// NextResetAtIn applies the In predicate on the "next_reset_at" field.
func NextResetAtIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldNextResetAt, vs...))
}

// NextResetAtNotIn applies the NotIn predicate on the "next_reset_at" field.
func NextResetAtNotIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldNextResetAt, vs...))
}

// NextResetAtGT applies the GT predicate on the "next_reset_at" field.
func NextResetAtGT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldNextResetAt, v))
}

// NextResetAtGTE applies the GTE predicate on the "next_reset_at" field.
func NextResetAtGTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldNextResetAt, v))
}

// NextResetAtLT applies the LT predicate on the "next_reset_at" field.
func NextResetAtLT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldNextResetAt, v))
}

// NextResetAtLTE applies the LTE predicate on the "next_reset_at" field.
func NextResetAtLTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldNextResetAt, v))
}

// NextResetAtIsNil applies the IsNil predicate on the "next_reset_at" field.
func NextResetAtIsNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIsNull(FieldNextResetAt))
}

// NextResetAtNotNil applies the NotNil predicate on the "next_reset_at" field.
func NextResetAtNotNil() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotNull(FieldNextResetAt))
}

// ReadyEQ applies the EQ predicate on the "ready" field.
func ReadyEQ(v bool) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldReady, v))
}

// ReadyNEQ applies the NEQ predicate on the "ready" field.
func ReadyNEQ(v bool) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldReady, v))
}

// NextCheckAtEQ applies the EQ predicate on the "next_check_at" field.
func NextCheckAtEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldEQ(FieldNextCheckAt, v))
}

// NextCheckAtNEQ applies the NEQ predicate on the "next_check_at" field.
func NextCheckAtNEQ(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNEQ(FieldNextCheckAt, v))
}

// NextCheckAtIn applies the In predicate on the "next_check_at" field.
func NextCheckAtIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldIn(FieldNextCheckAt, vs...))
}

// NextCheckAtNotIn applies the NotIn predicate on the "next_check_at" field.
func NextCheckAtNotIn(vs ...time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldNotIn(FieldNextCheckAt, vs...))
}

// NextCheckAtGT applies the GT predicate on the "next_check_at" field.
func NextCheckAtGT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGT(FieldNextCheckAt, v))
}

// NextCheckAtGTE applies the GTE predicate on the "next_check_at" field.
func NextCheckAtGTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldGTE(FieldNextCheckAt, v))
}

// NextCheckAtLT applies the LT predicate on the "next_check_at" field.
func NextCheckAtLT(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLT(FieldNextCheckAt, v))
}

// NextCheckAtLTE applies the LTE predicate on the "next_check_at" field.
func NextCheckAtLTE(v time.Time) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.FieldLTE(FieldNextCheckAt, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCredential applies the HasEdge predicate on the "credential" edge.
func HasCredential() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CredentialTable, CredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCredentialWith applies the HasEdge predicate on the "credential" edge with a given conditions (other predicates).
func HasCredentialWith(preds ...predicate.UpstreamCredential) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(func(s *sql.Selector) {
		step := newCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuotaScope applies the HasEdge predicate on the "quota_scope" edge.
func HasQuotaScope() predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuotaScopeTable, QuotaScopeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuotaScopeWith applies the HasEdge predicate on the "quota_scope" edge with a given conditions (other predicates).
func HasQuotaScopeWith(preds ...predicate.CredentialQuotaScope) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(func(s *sql.Selector) {
		step := newQuotaScopeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderQuotaStatus) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderQuotaStatus) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderQuotaStatus) predicate.ProviderQuotaStatus {
	return predicate.ProviderQuotaStatus(sql.NotPredicates(p))
}
