// Code generated by ent, DO NOT EDIT.

package upstreamcredential

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamcredential type in the database.
	Label = "upstream_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProviderType holds the string denoting the provider_type field in the database.
	FieldProviderType = "provider_type"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldAuthKind holds the string denoting the auth_kind field in the database.
	FieldAuthKind = "auth_kind"
	// FieldSecretKind holds the string denoting the secret_kind field in the database.
	FieldSecretKind = "secret_kind"
	// FieldIssuerScope holds the string denoting the issuer_scope field in the database.
	FieldIssuerScope = "issuer_scope"
	// FieldKeyHint holds the string denoting the key_hint field in the database.
	FieldKeyHint = "key_hint"
	// FieldQuotaScopeID holds the string denoting the quota_scope_id field in the database.
	FieldQuotaScopeID = "quota_scope_id"
	// FieldSecretPayload holds the string denoting the secret_payload field in the database.
	FieldSecretPayload = "secret_payload"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldSecretFingerprint holds the string denoting the secret_fingerprint field in the database.
	FieldSecretFingerprint = "secret_fingerprint"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldQuotaStatus holds the string denoting the quota_status field in the database.
	FieldQuotaStatus = "quota_status"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeChannelRefs holds the string denoting the channel_refs edge name in mutations.
	EdgeChannelRefs = "channel_refs"
	// EdgeExecutions holds the string denoting the executions edge name in mutations.
	EdgeExecutions = "executions"
	// EdgeUsageLogs holds the string denoting the usage_logs edge name in mutations.
	EdgeUsageLogs = "usage_logs"
	// EdgeQuotaScope holds the string denoting the quota_scope edge name in mutations.
	EdgeQuotaScope = "quota_scope"
	// Table holds the table name of the upstreamcredential in the database.
	Table = "upstream_credentials"
	// ChannelRefsTable is the table that holds the channel_refs relation/edge.
	ChannelRefsTable = "channel_credential_refs"
	// ChannelRefsInverseTable is the table name for the ChannelCredentialRef entity.
	// It exists in this package in order to avoid circular dependency with the "channelcredentialref" package.
	ChannelRefsInverseTable = "channel_credential_refs"
	// ChannelRefsColumn is the table column denoting the channel_refs relation/edge.
	ChannelRefsColumn = "credential_id"
	// ExecutionsTable is the table that holds the executions relation/edge.
	ExecutionsTable = "request_executions"
	// ExecutionsInverseTable is the table name for the RequestExecution entity.
	// It exists in this package in order to avoid circular dependency with the "requestexecution" package.
	ExecutionsInverseTable = "request_executions"
	// ExecutionsColumn is the table column denoting the executions relation/edge.
	ExecutionsColumn = "credential_id"
	// UsageLogsTable is the table that holds the usage_logs relation/edge.
	UsageLogsTable = "usage_logs"
	// UsageLogsInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogsInverseTable = "usage_logs"
	// UsageLogsColumn is the table column denoting the usage_logs relation/edge.
	UsageLogsColumn = "credential_id"
	// QuotaScopeTable is the table that holds the quota_scope relation/edge.
	QuotaScopeTable = "upstream_credentials"
	// QuotaScopeInverseTable is the table name for the CredentialQuotaScope entity.
	// It exists in this package in order to avoid circular dependency with the "credentialquotascope" package.
	QuotaScopeInverseTable = "credential_quota_scopes"
	// QuotaScopeColumn is the table column denoting the quota_scope relation/edge.
	QuotaScopeColumn = "quota_scope_id"
)

// Columns holds all SQL columns for upstreamcredential fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldProviderType,
	FieldBaseURL,
	FieldAuthKind,
	FieldSecretKind,
	FieldIssuerScope,
	FieldKeyHint,
	FieldQuotaScopeID,
	FieldSecretPayload,
	FieldFingerprint,
	FieldSecretFingerprint,
	FieldStatus,
	FieldWeight,
	FieldQuotaStatus,
	FieldLastError,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultProviderType holds the default value on creation for the "provider_type" field.
	DefaultProviderType string
	// DefaultBaseURL holds the default value on creation for the "base_url" field.
	DefaultBaseURL string
	// DefaultIssuerScope holds the default value on creation for the "issuer_scope" field.
	DefaultIssuerScope string
	// DefaultKeyHint holds the default value on creation for the "key_hint" field.
	DefaultKeyHint string
	// FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	FingerprintValidator func(string) error
	// SecretFingerprintValidator is a validator for the "secret_fingerprint" field. It is called by the builders before save.
	SecretFingerprintValidator func(string) error
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// DefaultQuotaStatus holds the default value on creation for the "quota_status" field.
	DefaultQuotaStatus string
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
)

// AuthKind defines the type for the "auth_kind" enum field.
type AuthKind string

// AuthKindAPIKey is the default value of the AuthKind enum.
const DefaultAuthKind = AuthKindAPIKey

// AuthKind values.
const (
	AuthKindAPIKey AuthKind = "api_key"
	AuthKindOauth  AuthKind = "oauth"
	AuthKindAzure  AuthKind = "azure"
	AuthKindGcp    AuthKind = "gcp"
	AuthKindOther  AuthKind = "other"
)

func (ak AuthKind) String() string {
	return string(ak)
}

// AuthKindValidator is a validator for the "auth_kind" field enum values. It is called by the builders before save.
func AuthKindValidator(ak AuthKind) error {
	switch ak {
	case AuthKindAPIKey, AuthKindOauth, AuthKindAzure, AuthKindGcp, AuthKindOther:
		return nil
	default:
		return fmt.Errorf("upstreamcredential: invalid enum value for auth_kind field: %q", ak)
	}
}

// SecretKind defines the type for the "secret_kind" enum field.
type SecretKind string

// SecretKindAPIKey is the default value of the SecretKind enum.
const DefaultSecretKind = SecretKindAPIKey

// SecretKind values.
const (
	SecretKindAPIKey SecretKind = "api_key"
	SecretKindOauth  SecretKind = "oauth"
	SecretKindAzure  SecretKind = "azure"
	SecretKindGcp    SecretKind = "gcp"
	SecretKindOther  SecretKind = "other"
)

func (sk SecretKind) String() string {
	return string(sk)
}

// SecretKindValidator is a validator for the "secret_kind" field enum values. It is called by the builders before save.
func SecretKindValidator(sk SecretKind) error {
	switch sk {
	case SecretKindAPIKey, SecretKindOauth, SecretKindAzure, SecretKindGcp, SecretKindOther:
		return nil
	default:
		return fmt.Errorf("upstreamcredential: invalid enum value for secret_kind field: %q", sk)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusEnabled is the default value of the Status enum.
const DefaultStatus = StatusEnabled

// Status values.
const (
	StatusEnabled  Status = "enabled"
	StatusDisabled Status = "disabled"
	StatusArchived Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusEnabled, StatusDisabled, StatusArchived:
		return nil
	default:
		return fmt.Errorf("upstreamcredential: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the UpstreamCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProviderType orders the results by the provider_type field.
func ByProviderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderType, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByAuthKind orders the results by the auth_kind field.
func ByAuthKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthKind, opts...).ToFunc()
}

// BySecretKind orders the results by the secret_kind field.
func BySecretKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretKind, opts...).ToFunc()
}

// ByIssuerScope orders the results by the issuer_scope field.
func ByIssuerScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuerScope, opts...).ToFunc()
}

// ByKeyHint orders the results by the key_hint field.
func ByKeyHint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyHint, opts...).ToFunc()
}

// ByQuotaScopeID orders the results by the quota_scope_id field.
func ByQuotaScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaScopeID, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// BySecretFingerprint orders the results by the secret_fingerprint field.
func BySecretFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretFingerprint, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByQuotaStatus orders the results by the quota_status field.
func ByQuotaStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaStatus, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByChannelRefsCount orders the results by channel_refs count.
func ByChannelRefsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelRefsStep(), opts...)
	}
}

// ByChannelRefs orders the results by channel_refs terms.
func ByChannelRefs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelRefsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExecutionsCount orders the results by executions count.
func ByExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExecutionsStep(), opts...)
	}
}

// ByExecutions orders the results by executions terms.
func ByExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsageLogsCount orders the results by usage_logs count.
func ByUsageLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageLogsStep(), opts...)
	}
}

// ByUsageLogs orders the results by usage_logs terms.
func ByUsageLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQuotaScopeField orders the results by quota_scope field.
func ByQuotaScopeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuotaScopeStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelRefsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelRefsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChannelRefsTable, ChannelRefsColumn),
	)
}
func newExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExecutionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExecutionsTable, ExecutionsColumn),
	)
}
func newUsageLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
	)
}
func newQuotaScopeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuotaScopeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuotaScopeTable, QuotaScopeColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e AuthKind) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *AuthKind) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = AuthKind(str)
	if err := AuthKindValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid AuthKind", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e SecretKind) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *SecretKind) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = SecretKind(str)
	if err := SecretKindValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid SecretKind", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
