package openapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/contexts"
	"github.com/looplj/axonhub/internal/objects"
)

// RouteTiers is the resolver for the routeTiers field.
func (r *aPIKeyProfileResolver) RouteTiers(ctx context.Context, obj *objects.APIKeyProfile) ([]*APIKeyRouteTier, error) {
	if obj == nil || len(obj.RouteTiers) == 0 {
		return nil, nil
	}

	result := make([]*APIKeyRouteTier, 0, len(obj.RouteTiers))
	for _, tier := range obj.RouteTiers {
		result = append(result, &APIKeyRouteTier{
			Name:       tier.Name,
			ChannelIDs: append([]int(nil), tier.ChannelIDs...),
		})
	}

	return result, nil
}

// RouteMigration is the resolver for the routeMigration field.
func (r *aPIKeyProfileResolver) RouteMigration(ctx context.Context, obj *objects.APIKeyProfile) (*APIKeyRouteMigration, error) {
	if obj == nil || obj.RouteMigration == nil {
		return nil, nil
	}

	return &APIKeyRouteMigration{
		Version: obj.RouteMigration.Version,
		Source:  obj.RouteMigration.Source,
	}, nil
}

// CreateLLMAPIKey is the resolver for the createLLMAPIKey field.
func (r *mutationResolver) CreateLLMAPIKey(ctx context.Context, name string) (*APIKey, error) {
	ownerKey, ok := contexts.GetAPIKey(ctx)
	if !ok || ownerKey == nil {
		return nil, fmt.Errorf("api key not found in context")
	}

	apiKey, err := r.apiKeyService.CreateLLMAPIKey(ctx, ownerKey, name)
	if err != nil {
		return nil, err
	}

	return toOpenAPIAPIKey(apiKey), nil
}

// UpdateAPIKeyProfiles is the resolver for the updateAPIKeyProfiles field.
func (r *mutationResolver) UpdateAPIKeyProfiles(ctx context.Context, id objects.GUID, input objects.APIKeyProfiles) (*APIKey, error) {
	// Coerce nil ModelMappings to [] before saving. The admin UI's Zod schema
	// rejects null/undefined for this specific field (other arrays are .nullable),
	// so OpenAPI clients omitting modelMappings would otherwise produce rows
	// the UI can't render. This is scoped to OpenAPI because admin GraphQL
	// inputs are validated client-side and never carry nil here.
	for i := range input.Profiles {
		if input.Profiles[i].ModelMappings == nil {
			input.Profiles[i].ModelMappings = []objects.ModelMapping{}
		}
	}

	apiKey, err := r.apiKeyService.UpdateAPIKeyProfiles(ctx, id.ID, input)
	if err != nil {
		return nil, err
	}

	return toOpenAPIAPIKey(apiKey), nil
}

// LoadAPIKeyProfileTemplate is the resolver for the loadApiKeyProfileTemplate field.
func (r *mutationResolver) LoadAPIKeyProfileTemplate(ctx context.Context, input LoadAPIKeyProfileTemplateInput) (*APIKey, error) {
	apiKey, err := r.apiKeyProfileTemplateService.LoadTemplate(ctx, input.TemplateID.ID, input.APIKeyID.ID)
	if err != nil {
		return nil, err
	}

	return toOpenAPIAPIKey(apiKey), nil
}

// RouteTiers is the resolver for the routeTiers field.
func (r *aPIKeyProfileInputResolver) RouteTiers(ctx context.Context, obj *objects.APIKeyProfile, data []*APIKeyRouteTierInput) error {
	if obj == nil {
		return nil
	}

	if len(data) == 0 {
		obj.RouteTiers = nil
		return nil
	}

	obj.RouteTiers = make([]objects.APIKeyRouteTier, 0, len(data))
	for _, tier := range data {
		if tier == nil {
			continue
		}
		obj.RouteTiers = append(obj.RouteTiers, objects.APIKeyRouteTier{
			Name:       tier.Name,
			ChannelIDs: append([]int(nil), tier.ChannelIDs...),
		})
	}

	return nil
}

// APIKeyProfile returns APIKeyProfileResolver implementation.
func (r *Resolver) APIKeyProfile() APIKeyProfileResolver { return &aPIKeyProfileResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// APIKeyProfileInput returns APIKeyProfileInputResolver implementation.
func (r *Resolver) APIKeyProfileInput() APIKeyProfileInputResolver {
	return &aPIKeyProfileInputResolver{r}
}

type aPIKeyProfileResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type aPIKeyProfileInputResolver struct{ *Resolver }
