// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelcredentialref"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/upstreamcredential"
)

// ChannelCredentialRefQuery is the builder for querying ChannelCredentialRef entities.
type ChannelCredentialRefQuery struct {
	config
	ctx            *QueryContext
	order          []channelcredentialref.OrderOption
	inters         []Interceptor
	predicates     []predicate.ChannelCredentialRef
	withChannel    *ChannelQuery
	withCredential *UpstreamCredentialQuery
	loadTotal      []func(context.Context, []*ChannelCredentialRef) error
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChannelCredentialRefQuery builder.
func (_q *ChannelCredentialRefQuery) Where(ps ...predicate.ChannelCredentialRef) *ChannelCredentialRefQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChannelCredentialRefQuery) Limit(limit int) *ChannelCredentialRefQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChannelCredentialRefQuery) Offset(offset int) *ChannelCredentialRefQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChannelCredentialRefQuery) Unique(unique bool) *ChannelCredentialRefQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChannelCredentialRefQuery) Order(o ...channelcredentialref.OrderOption) *ChannelCredentialRefQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChannel chains the current query on the "channel" edge.
func (_q *ChannelCredentialRefQuery) QueryChannel() *ChannelQuery {
	query := (&ChannelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channelcredentialref.Table, channelcredentialref.FieldID, selector),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelcredentialref.ChannelTable, channelcredentialref.ChannelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCredential chains the current query on the "credential" edge.
func (_q *ChannelCredentialRefQuery) QueryCredential() *UpstreamCredentialQuery {
	query := (&UpstreamCredentialClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channelcredentialref.Table, channelcredentialref.FieldID, selector),
			sqlgraph.To(upstreamcredential.Table, upstreamcredential.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelcredentialref.CredentialTable, channelcredentialref.CredentialColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChannelCredentialRef entity from the query.
// Returns a *NotFoundError when no ChannelCredentialRef was found.
func (_q *ChannelCredentialRefQuery) First(ctx context.Context) (*ChannelCredentialRef, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{channelcredentialref.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) FirstX(ctx context.Context) *ChannelCredentialRef {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChannelCredentialRef ID from the query.
// Returns a *NotFoundError when no ChannelCredentialRef ID was found.
func (_q *ChannelCredentialRefQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{channelcredentialref.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChannelCredentialRef entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChannelCredentialRef entity is found.
// Returns a *NotFoundError when no ChannelCredentialRef entities are found.
func (_q *ChannelCredentialRefQuery) Only(ctx context.Context) (*ChannelCredentialRef, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{channelcredentialref.Label}
	default:
		return nil, &NotSingularError{channelcredentialref.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) OnlyX(ctx context.Context) *ChannelCredentialRef {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChannelCredentialRef ID in the query.
// Returns a *NotSingularError when more than one ChannelCredentialRef ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChannelCredentialRefQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{channelcredentialref.Label}
	default:
		err = &NotSingularError{channelcredentialref.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChannelCredentialRefs.
func (_q *ChannelCredentialRefQuery) All(ctx context.Context) ([]*ChannelCredentialRef, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChannelCredentialRef, *ChannelCredentialRefQuery]()
	return withInterceptors[[]*ChannelCredentialRef](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) AllX(ctx context.Context) []*ChannelCredentialRef {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChannelCredentialRef IDs.
func (_q *ChannelCredentialRefQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(channelcredentialref.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChannelCredentialRefQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChannelCredentialRefQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChannelCredentialRefQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChannelCredentialRefQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChannelCredentialRefQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChannelCredentialRefQuery) Clone() *ChannelCredentialRefQuery {
	if _q == nil {
		return nil
	}
	return &ChannelCredentialRefQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]channelcredentialref.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.ChannelCredentialRef{}, _q.predicates...),
		withChannel:    _q.withChannel.Clone(),
		withCredential: _q.withCredential.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithChannel tells the query-builder to eager-load the nodes that are connected to
// the "channel" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelCredentialRefQuery) WithChannel(opts ...func(*ChannelQuery)) *ChannelCredentialRefQuery {
	query := (&ChannelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChannel = query
	return _q
}

// WithCredential tells the query-builder to eager-load the nodes that are connected to
// the "credential" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelCredentialRefQuery) WithCredential(opts ...func(*UpstreamCredentialQuery)) *ChannelCredentialRefQuery {
	query := (&UpstreamCredentialClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCredential = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChannelCredentialRef.Query().
//		GroupBy(channelcredentialref.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChannelCredentialRefQuery) GroupBy(field string, fields ...string) *ChannelCredentialRefGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChannelCredentialRefGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = channelcredentialref.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ChannelCredentialRef.Query().
//		Select(channelcredentialref.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ChannelCredentialRefQuery) Select(fields ...string) *ChannelCredentialRefSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChannelCredentialRefSelect{ChannelCredentialRefQuery: _q}
	sbuild.label = channelcredentialref.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChannelCredentialRefSelect configured with the given aggregations.
func (_q *ChannelCredentialRefQuery) Aggregate(fns ...AggregateFunc) *ChannelCredentialRefSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChannelCredentialRefQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !channelcredentialref.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if channelcredentialref.Policy == nil {
		return errors.New("ent: uninitialized channelcredentialref.Policy (forgotten import ent/runtime?)")
	}
	if err := channelcredentialref.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *ChannelCredentialRefQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChannelCredentialRef, error) {
	var (
		nodes       = []*ChannelCredentialRef{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withChannel != nil,
			_q.withCredential != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChannelCredentialRef).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChannelCredentialRef{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChannel; query != nil {
		if err := _q.loadChannel(ctx, query, nodes, nil,
			func(n *ChannelCredentialRef, e *Channel) { n.Edges.Channel = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCredential; query != nil {
		if err := _q.loadCredential(ctx, query, nodes, nil,
			func(n *ChannelCredentialRef, e *UpstreamCredential) { n.Edges.Credential = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChannelCredentialRefQuery) loadChannel(ctx context.Context, query *ChannelQuery, nodes []*ChannelCredentialRef, init func(*ChannelCredentialRef), assign func(*ChannelCredentialRef, *Channel)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChannelCredentialRef)
	for i := range nodes {
		fk := nodes[i].ChannelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(channel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "channel_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChannelCredentialRefQuery) loadCredential(ctx context.Context, query *UpstreamCredentialQuery, nodes []*ChannelCredentialRef, init func(*ChannelCredentialRef), assign func(*ChannelCredentialRef, *UpstreamCredential)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChannelCredentialRef)
	for i := range nodes {
		fk := nodes[i].CredentialID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(upstreamcredential.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "credential_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChannelCredentialRefQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChannelCredentialRefQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(channelcredentialref.Table, channelcredentialref.Columns, sqlgraph.NewFieldSpec(channelcredentialref.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelcredentialref.FieldID)
		for i := range fields {
			if fields[i] != channelcredentialref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChannel != nil {
			_spec.Node.AddColumnOnce(channelcredentialref.FieldChannelID)
		}
		if _q.withCredential != nil {
			_spec.Node.AddColumnOnce(channelcredentialref.FieldCredentialID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChannelCredentialRefQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(channelcredentialref.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = channelcredentialref.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ChannelCredentialRefQuery) Modify(modifiers ...func(s *sql.Selector)) *ChannelCredentialRefSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// ChannelCredentialRefGroupBy is the group-by builder for ChannelCredentialRef entities.
type ChannelCredentialRefGroupBy struct {
	selector
	build *ChannelCredentialRefQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChannelCredentialRefGroupBy) Aggregate(fns ...AggregateFunc) *ChannelCredentialRefGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChannelCredentialRefGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelCredentialRefQuery, *ChannelCredentialRefGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChannelCredentialRefGroupBy) sqlScan(ctx context.Context, root *ChannelCredentialRefQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChannelCredentialRefSelect is the builder for selecting fields of ChannelCredentialRef entities.
type ChannelCredentialRefSelect struct {
	*ChannelCredentialRefQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChannelCredentialRefSelect) Aggregate(fns ...AggregateFunc) *ChannelCredentialRefSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChannelCredentialRefSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelCredentialRefQuery, *ChannelCredentialRefSelect](ctx, _s.ChannelCredentialRefQuery, _s, _s.inters, v)
}

func (_s *ChannelCredentialRefSelect) sqlScan(ctx context.Context, root *ChannelCredentialRefQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ChannelCredentialRefSelect) Modify(modifiers ...func(s *sql.Selector)) *ChannelCredentialRefSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
