// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channelcredentialref"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ChannelCredentialRefUpdate is the builder for updating ChannelCredentialRef entities.
type ChannelCredentialRefUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelCredentialRefMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelCredentialRefUpdate builder.
func (_u *ChannelCredentialRefUpdate) Where(ps ...predicate.ChannelCredentialRef) *ChannelCredentialRefUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelCredentialRefUpdate) SetUpdatedAt(v time.Time) *ChannelCredentialRefUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelCredentialRefUpdate) SetEnabled(v bool) *ChannelCredentialRefUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelCredentialRefUpdate) SetNillableEnabled(v *bool) *ChannelCredentialRefUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetWeightOverride sets the "weight_override" field.
func (_u *ChannelCredentialRefUpdate) SetWeightOverride(v int) *ChannelCredentialRefUpdate {
	_u.mutation.ResetWeightOverride()
	_u.mutation.SetWeightOverride(v)
	return _u
}

// SetNillableWeightOverride sets the "weight_override" field if the given value is not nil.
func (_u *ChannelCredentialRefUpdate) SetNillableWeightOverride(v *int) *ChannelCredentialRefUpdate {
	if v != nil {
		_u.SetWeightOverride(*v)
	}
	return _u
}

// AddWeightOverride adds value to the "weight_override" field.
func (_u *ChannelCredentialRefUpdate) AddWeightOverride(v int) *ChannelCredentialRefUpdate {
	_u.mutation.AddWeightOverride(v)
	return _u
}

// ClearWeightOverride clears the value of the "weight_override" field.
func (_u *ChannelCredentialRefUpdate) ClearWeightOverride() *ChannelCredentialRefUpdate {
	_u.mutation.ClearWeightOverride()
	return _u
}

// Mutation returns the ChannelCredentialRefMutation object of the builder.
func (_u *ChannelCredentialRefUpdate) Mutation() *ChannelCredentialRefMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelCredentialRefUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelCredentialRefUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelCredentialRefUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelCredentialRefUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelCredentialRefUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelcredentialref.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelcredentialref.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelcredentialref.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelCredentialRefUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCredentialRef.channel"`)
	}
	if _u.mutation.CredentialCleared() && len(_u.mutation.CredentialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCredentialRef.credential"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelCredentialRefUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelCredentialRefUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelCredentialRefUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelcredentialref.Table, channelcredentialref.Columns, sqlgraph.NewFieldSpec(channelcredentialref.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelcredentialref.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelcredentialref.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WeightOverride(); ok {
		_spec.SetField(channelcredentialref.FieldWeightOverride, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeightOverride(); ok {
		_spec.AddField(channelcredentialref.FieldWeightOverride, field.TypeInt, value)
	}
	if _u.mutation.WeightOverrideCleared() {
		_spec.ClearField(channelcredentialref.FieldWeightOverride, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelcredentialref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelCredentialRefUpdateOne is the builder for updating a single ChannelCredentialRef entity.
type ChannelCredentialRefUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelCredentialRefMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelCredentialRefUpdateOne) SetUpdatedAt(v time.Time) *ChannelCredentialRefUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelCredentialRefUpdateOne) SetEnabled(v bool) *ChannelCredentialRefUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelCredentialRefUpdateOne) SetNillableEnabled(v *bool) *ChannelCredentialRefUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetWeightOverride sets the "weight_override" field.
func (_u *ChannelCredentialRefUpdateOne) SetWeightOverride(v int) *ChannelCredentialRefUpdateOne {
	_u.mutation.ResetWeightOverride()
	_u.mutation.SetWeightOverride(v)
	return _u
}

// SetNillableWeightOverride sets the "weight_override" field if the given value is not nil.
func (_u *ChannelCredentialRefUpdateOne) SetNillableWeightOverride(v *int) *ChannelCredentialRefUpdateOne {
	if v != nil {
		_u.SetWeightOverride(*v)
	}
	return _u
}

// AddWeightOverride adds value to the "weight_override" field.
func (_u *ChannelCredentialRefUpdateOne) AddWeightOverride(v int) *ChannelCredentialRefUpdateOne {
	_u.mutation.AddWeightOverride(v)
	return _u
}

// ClearWeightOverride clears the value of the "weight_override" field.
func (_u *ChannelCredentialRefUpdateOne) ClearWeightOverride() *ChannelCredentialRefUpdateOne {
	_u.mutation.ClearWeightOverride()
	return _u
}

// Mutation returns the ChannelCredentialRefMutation object of the builder.
func (_u *ChannelCredentialRefUpdateOne) Mutation() *ChannelCredentialRefMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelCredentialRefUpdate builder.
func (_u *ChannelCredentialRefUpdateOne) Where(ps ...predicate.ChannelCredentialRef) *ChannelCredentialRefUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelCredentialRefUpdateOne) Select(field string, fields ...string) *ChannelCredentialRefUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelCredentialRef entity.
func (_u *ChannelCredentialRefUpdateOne) Save(ctx context.Context) (*ChannelCredentialRef, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelCredentialRefUpdateOne) SaveX(ctx context.Context) *ChannelCredentialRef {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelCredentialRefUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelCredentialRefUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelCredentialRefUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelcredentialref.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelcredentialref.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelcredentialref.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelCredentialRefUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCredentialRef.channel"`)
	}
	if _u.mutation.CredentialCleared() && len(_u.mutation.CredentialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelCredentialRef.credential"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelCredentialRefUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelCredentialRefUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelCredentialRefUpdateOne) sqlSave(ctx context.Context) (_node *ChannelCredentialRef, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelcredentialref.Table, channelcredentialref.Columns, sqlgraph.NewFieldSpec(channelcredentialref.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelCredentialRef.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelcredentialref.FieldID)
		for _, f := range fields {
			if !channelcredentialref.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelcredentialref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelcredentialref.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelcredentialref.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WeightOverride(); ok {
		_spec.SetField(channelcredentialref.FieldWeightOverride, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeightOverride(); ok {
		_spec.AddField(channelcredentialref.FieldWeightOverride, field.TypeInt, value)
	}
	if _u.mutation.WeightOverrideCleared() {
		_spec.ClearField(channelcredentialref.FieldWeightOverride, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChannelCredentialRef{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelcredentialref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
