// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/credentialquotascope"
)

// CredentialQuotaScope is the model entity for the CredentialQuotaScope schema.
type CredentialQuotaScope struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status credentialquotascope.Status `json:"status,omitempty"`
	// Unit holds the value of the "unit" field.
	Unit credentialquotascope.Unit `json:"unit,omitempty"`
	// Configured quota limit stored as decimal text to avoid precision loss
	LimitAmount string `json:"limit_amount,omitempty"`
	// Current quota usage stored as decimal text to avoid precision loss
	UsedAmount string `json:"used_amount,omitempty"`
	// Warning threshold percentage for local budget scopes
	WarningThresholdPercent *int `json:"warning_threshold_percent,omitempty"`
	// ResetPolicy holds the value of the "reset_policy" field.
	ResetPolicy credentialquotascope.ResetPolicy `json:"reset_policy,omitempty"`
	// ResetAt holds the value of the "reset_at" field.
	ResetAt *time.Time `json:"reset_at,omitempty"`
	// WindowStartedAt holds the value of the "window_started_at" field.
	WindowStartedAt *time.Time `json:"window_started_at,omitempty"`
	// OverLimitAction holds the value of the "over_limit_action" field.
	OverLimitAction credentialquotascope.OverLimitAction `json:"over_limit_action,omitempty"`
	// PauseUntil holds the value of the "pause_until" field.
	PauseUntil *time.Time `json:"pause_until,omitempty"`
	// Source holds the value of the "source" field.
	Source credentialquotascope.Source `json:"source,omitempty"`
	// Latest quota error safe for operator display
	LastError string `json:"last_error,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CredentialQuotaScopeQuery when eager-loading is set.
	Edges        CredentialQuotaScopeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CredentialQuotaScopeEdges holds the relations/edges for other nodes in the graph.
type CredentialQuotaScopeEdges struct {
	// Credentials holds the value of the credentials edge.
	Credentials []*UpstreamCredential `json:"credentials,omitempty"`
	// ProviderQuotaStatuses holds the value of the provider_quota_statuses edge.
	ProviderQuotaStatuses []*ProviderQuotaStatus `json:"provider_quota_statuses,omitempty"`
	// Executions holds the value of the executions edge.
	Executions []*RequestExecution `json:"executions,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int

	namedCredentials           map[string][]*UpstreamCredential
	namedProviderQuotaStatuses map[string][]*ProviderQuotaStatus
	namedExecutions            map[string][]*RequestExecution
	namedUsageLogs             map[string][]*UsageLog
}

// CredentialsOrErr returns the Credentials value or an error if the edge
// was not loaded in eager-loading.
func (e CredentialQuotaScopeEdges) CredentialsOrErr() ([]*UpstreamCredential, error) {
	if e.loadedTypes[0] {
		return e.Credentials, nil
	}
	return nil, &NotLoadedError{edge: "credentials"}
}

// ProviderQuotaStatusesOrErr returns the ProviderQuotaStatuses value or an error if the edge
// was not loaded in eager-loading.
func (e CredentialQuotaScopeEdges) ProviderQuotaStatusesOrErr() ([]*ProviderQuotaStatus, error) {
	if e.loadedTypes[1] {
		return e.ProviderQuotaStatuses, nil
	}
	return nil, &NotLoadedError{edge: "provider_quota_statuses"}
}

// ExecutionsOrErr returns the Executions value or an error if the edge
// was not loaded in eager-loading.
func (e CredentialQuotaScopeEdges) ExecutionsOrErr() ([]*RequestExecution, error) {
	if e.loadedTypes[2] {
		return e.Executions, nil
	}
	return nil, &NotLoadedError{edge: "executions"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e CredentialQuotaScopeEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[3] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CredentialQuotaScope) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case credentialquotascope.FieldID, credentialquotascope.FieldDeletedAt, credentialquotascope.FieldWarningThresholdPercent:
			values[i] = new(sql.NullInt64)
		case credentialquotascope.FieldName, credentialquotascope.FieldStatus, credentialquotascope.FieldUnit, credentialquotascope.FieldLimitAmount, credentialquotascope.FieldUsedAmount, credentialquotascope.FieldResetPolicy, credentialquotascope.FieldOverLimitAction, credentialquotascope.FieldSource, credentialquotascope.FieldLastError, credentialquotascope.FieldRemark:
			values[i] = new(sql.NullString)
		case credentialquotascope.FieldCreatedAt, credentialquotascope.FieldUpdatedAt, credentialquotascope.FieldResetAt, credentialquotascope.FieldWindowStartedAt, credentialquotascope.FieldPauseUntil:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CredentialQuotaScope fields.
func (_m *CredentialQuotaScope) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case credentialquotascope.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case credentialquotascope.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case credentialquotascope.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case credentialquotascope.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case credentialquotascope.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case credentialquotascope.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = credentialquotascope.Status(value.String)
			}
		case credentialquotascope.FieldUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unit", values[i])
			} else if value.Valid {
				_m.Unit = credentialquotascope.Unit(value.String)
			}
		case credentialquotascope.FieldLimitAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field limit_amount", values[i])
			} else if value.Valid {
				_m.LimitAmount = value.String
			}
		case credentialquotascope.FieldUsedAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field used_amount", values[i])
			} else if value.Valid {
				_m.UsedAmount = value.String
			}
		case credentialquotascope.FieldWarningThresholdPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field warning_threshold_percent", values[i])
			} else if value.Valid {
				_m.WarningThresholdPercent = new(int)
				*_m.WarningThresholdPercent = int(value.Int64)
			}
		case credentialquotascope.FieldResetPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reset_policy", values[i])
			} else if value.Valid {
				_m.ResetPolicy = credentialquotascope.ResetPolicy(value.String)
			}
		case credentialquotascope.FieldResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reset_at", values[i])
			} else if value.Valid {
				_m.ResetAt = new(time.Time)
				*_m.ResetAt = value.Time
			}
		case credentialquotascope.FieldWindowStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_started_at", values[i])
			} else if value.Valid {
				_m.WindowStartedAt = new(time.Time)
				*_m.WindowStartedAt = value.Time
			}
		case credentialquotascope.FieldOverLimitAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field over_limit_action", values[i])
			} else if value.Valid {
				_m.OverLimitAction = credentialquotascope.OverLimitAction(value.String)
			}
		case credentialquotascope.FieldPauseUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field pause_until", values[i])
			} else if value.Valid {
				_m.PauseUntil = new(time.Time)
				*_m.PauseUntil = value.Time
			}
		case credentialquotascope.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = credentialquotascope.Source(value.String)
			}
		case credentialquotascope.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case credentialquotascope.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CredentialQuotaScope.
// This includes values selected through modifiers, order, etc.
func (_m *CredentialQuotaScope) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCredentials queries the "credentials" edge of the CredentialQuotaScope entity.
func (_m *CredentialQuotaScope) QueryCredentials() *UpstreamCredentialQuery {
	return NewCredentialQuotaScopeClient(_m.config).QueryCredentials(_m)
}

// QueryProviderQuotaStatuses queries the "provider_quota_statuses" edge of the CredentialQuotaScope entity.
func (_m *CredentialQuotaScope) QueryProviderQuotaStatuses() *ProviderQuotaStatusQuery {
	return NewCredentialQuotaScopeClient(_m.config).QueryProviderQuotaStatuses(_m)
}

// QueryExecutions queries the "executions" edge of the CredentialQuotaScope entity.
func (_m *CredentialQuotaScope) QueryExecutions() *RequestExecutionQuery {
	return NewCredentialQuotaScopeClient(_m.config).QueryExecutions(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the CredentialQuotaScope entity.
func (_m *CredentialQuotaScope) QueryUsageLogs() *UsageLogQuery {
	return NewCredentialQuotaScopeClient(_m.config).QueryUsageLogs(_m)
}

// Update returns a builder for updating this CredentialQuotaScope.
// Note that you need to call CredentialQuotaScope.Unwrap() before calling this method if this CredentialQuotaScope
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CredentialQuotaScope) Update() *CredentialQuotaScopeUpdateOne {
	return NewCredentialQuotaScopeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CredentialQuotaScope entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CredentialQuotaScope) Unwrap() *CredentialQuotaScope {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CredentialQuotaScope is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CredentialQuotaScope) String() string {
	var builder strings.Builder
	builder.WriteString("CredentialQuotaScope(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("unit=")
	builder.WriteString(fmt.Sprintf("%v", _m.Unit))
	builder.WriteString(", ")
	builder.WriteString("limit_amount=")
	builder.WriteString(_m.LimitAmount)
	builder.WriteString(", ")
	builder.WriteString("used_amount=")
	builder.WriteString(_m.UsedAmount)
	builder.WriteString(", ")
	if v := _m.WarningThresholdPercent; v != nil {
		builder.WriteString("warning_threshold_percent=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reset_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResetPolicy))
	builder.WriteString(", ")
	if v := _m.ResetAt; v != nil {
		builder.WriteString("reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WindowStartedAt; v != nil {
		builder.WriteString("window_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("over_limit_action=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverLimitAction))
	builder.WriteString(", ")
	if v := _m.PauseUntil; v != nil {
		builder.WriteString("pause_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteByte(')')
	return builder.String()
}

// NamedCredentials returns the Credentials named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *CredentialQuotaScope) NamedCredentials(name string) ([]*UpstreamCredential, error) {
	if _m.Edges.namedCredentials == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedCredentials[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *CredentialQuotaScope) appendNamedCredentials(name string, edges ...*UpstreamCredential) {
	if _m.Edges.namedCredentials == nil {
		_m.Edges.namedCredentials = make(map[string][]*UpstreamCredential)
	}
	if len(edges) == 0 {
		_m.Edges.namedCredentials[name] = []*UpstreamCredential{}
	} else {
		_m.Edges.namedCredentials[name] = append(_m.Edges.namedCredentials[name], edges...)
	}
}

// NamedProviderQuotaStatuses returns the ProviderQuotaStatuses named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *CredentialQuotaScope) NamedProviderQuotaStatuses(name string) ([]*ProviderQuotaStatus, error) {
	if _m.Edges.namedProviderQuotaStatuses == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedProviderQuotaStatuses[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *CredentialQuotaScope) appendNamedProviderQuotaStatuses(name string, edges ...*ProviderQuotaStatus) {
	if _m.Edges.namedProviderQuotaStatuses == nil {
		_m.Edges.namedProviderQuotaStatuses = make(map[string][]*ProviderQuotaStatus)
	}
	if len(edges) == 0 {
		_m.Edges.namedProviderQuotaStatuses[name] = []*ProviderQuotaStatus{}
	} else {
		_m.Edges.namedProviderQuotaStatuses[name] = append(_m.Edges.namedProviderQuotaStatuses[name], edges...)
	}
}

// NamedExecutions returns the Executions named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *CredentialQuotaScope) NamedExecutions(name string) ([]*RequestExecution, error) {
	if _m.Edges.namedExecutions == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedExecutions[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *CredentialQuotaScope) appendNamedExecutions(name string, edges ...*RequestExecution) {
	if _m.Edges.namedExecutions == nil {
		_m.Edges.namedExecutions = make(map[string][]*RequestExecution)
	}
	if len(edges) == 0 {
		_m.Edges.namedExecutions[name] = []*RequestExecution{}
	} else {
		_m.Edges.namedExecutions[name] = append(_m.Edges.namedExecutions[name], edges...)
	}
}

// NamedUsageLogs returns the UsageLogs named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *CredentialQuotaScope) NamedUsageLogs(name string) ([]*UsageLog, error) {
	if _m.Edges.namedUsageLogs == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUsageLogs[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *CredentialQuotaScope) appendNamedUsageLogs(name string, edges ...*UsageLog) {
	if _m.Edges.namedUsageLogs == nil {
		_m.Edges.namedUsageLogs = make(map[string][]*UsageLog)
	}
	if len(edges) == 0 {
		_m.Edges.namedUsageLogs[name] = []*UsageLog{}
	} else {
		_m.Edges.namedUsageLogs[name] = append(_m.Edges.namedUsageLogs[name], edges...)
	}
}

// CredentialQuotaScopes is a parsable slice of CredentialQuotaScope.
type CredentialQuotaScopes []*CredentialQuotaScope
