// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/credentialquotascope"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/ent/upstreamcredential"
	"github.com/looplj/axonhub/internal/ent/usagelog"
)

// CredentialQuotaScopeUpdate is the builder for updating CredentialQuotaScope entities.
type CredentialQuotaScopeUpdate struct {
	config
	hooks     []Hook
	mutation  *CredentialQuotaScopeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CredentialQuotaScopeUpdate builder.
func (_u *CredentialQuotaScopeUpdate) Where(ps ...predicate.CredentialQuotaScope) *CredentialQuotaScopeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialQuotaScopeUpdate) SetUpdatedAt(v time.Time) *CredentialQuotaScopeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CredentialQuotaScopeUpdate) SetDeletedAt(v int) *CredentialQuotaScopeUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableDeletedAt(v *int) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *CredentialQuotaScopeUpdate) AddDeletedAt(v int) *CredentialQuotaScopeUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CredentialQuotaScopeUpdate) SetName(v string) *CredentialQuotaScopeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableName(v *string) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *CredentialQuotaScopeUpdate) ClearName() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CredentialQuotaScopeUpdate) SetStatus(v credentialquotascope.Status) *CredentialQuotaScopeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableStatus(v *credentialquotascope.Status) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUnit sets the "unit" field.
func (_u *CredentialQuotaScopeUpdate) SetUnit(v credentialquotascope.Unit) *CredentialQuotaScopeUpdate {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableUnit(v *credentialquotascope.Unit) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// SetLimitAmount sets the "limit_amount" field.
func (_u *CredentialQuotaScopeUpdate) SetLimitAmount(v string) *CredentialQuotaScopeUpdate {
	_u.mutation.SetLimitAmount(v)
	return _u
}

// SetNillableLimitAmount sets the "limit_amount" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableLimitAmount(v *string) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetLimitAmount(*v)
	}
	return _u
}

// ClearLimitAmount clears the value of the "limit_amount" field.
func (_u *CredentialQuotaScopeUpdate) ClearLimitAmount() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearLimitAmount()
	return _u
}

// SetUsedAmount sets the "used_amount" field.
func (_u *CredentialQuotaScopeUpdate) SetUsedAmount(v string) *CredentialQuotaScopeUpdate {
	_u.mutation.SetUsedAmount(v)
	return _u
}

// SetNillableUsedAmount sets the "used_amount" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableUsedAmount(v *string) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetUsedAmount(*v)
	}
	return _u
}

// ClearUsedAmount clears the value of the "used_amount" field.
func (_u *CredentialQuotaScopeUpdate) ClearUsedAmount() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearUsedAmount()
	return _u
}

// SetWarningThresholdPercent sets the "warning_threshold_percent" field.
func (_u *CredentialQuotaScopeUpdate) SetWarningThresholdPercent(v int) *CredentialQuotaScopeUpdate {
	_u.mutation.ResetWarningThresholdPercent()
	_u.mutation.SetWarningThresholdPercent(v)
	return _u
}

// SetNillableWarningThresholdPercent sets the "warning_threshold_percent" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableWarningThresholdPercent(v *int) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetWarningThresholdPercent(*v)
	}
	return _u
}

// AddWarningThresholdPercent adds value to the "warning_threshold_percent" field.
func (_u *CredentialQuotaScopeUpdate) AddWarningThresholdPercent(v int) *CredentialQuotaScopeUpdate {
	_u.mutation.AddWarningThresholdPercent(v)
	return _u
}

// ClearWarningThresholdPercent clears the value of the "warning_threshold_percent" field.
func (_u *CredentialQuotaScopeUpdate) ClearWarningThresholdPercent() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearWarningThresholdPercent()
	return _u
}

// SetResetPolicy sets the "reset_policy" field.
func (_u *CredentialQuotaScopeUpdate) SetResetPolicy(v credentialquotascope.ResetPolicy) *CredentialQuotaScopeUpdate {
	_u.mutation.SetResetPolicy(v)
	return _u
}

// SetNillableResetPolicy sets the "reset_policy" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableResetPolicy(v *credentialquotascope.ResetPolicy) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetResetPolicy(*v)
	}
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *CredentialQuotaScopeUpdate) SetResetAt(v time.Time) *CredentialQuotaScopeUpdate {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableResetAt(v *time.Time) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *CredentialQuotaScopeUpdate) ClearResetAt() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearResetAt()
	return _u
}

// SetWindowStartedAt sets the "window_started_at" field.
func (_u *CredentialQuotaScopeUpdate) SetWindowStartedAt(v time.Time) *CredentialQuotaScopeUpdate {
	_u.mutation.SetWindowStartedAt(v)
	return _u
}

// SetNillableWindowStartedAt sets the "window_started_at" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableWindowStartedAt(v *time.Time) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetWindowStartedAt(*v)
	}
	return _u
}

// ClearWindowStartedAt clears the value of the "window_started_at" field.
func (_u *CredentialQuotaScopeUpdate) ClearWindowStartedAt() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearWindowStartedAt()
	return _u
}

// SetOverLimitAction sets the "over_limit_action" field.
func (_u *CredentialQuotaScopeUpdate) SetOverLimitAction(v credentialquotascope.OverLimitAction) *CredentialQuotaScopeUpdate {
	_u.mutation.SetOverLimitAction(v)
	return _u
}

// SetNillableOverLimitAction sets the "over_limit_action" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableOverLimitAction(v *credentialquotascope.OverLimitAction) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetOverLimitAction(*v)
	}
	return _u
}

// SetPauseUntil sets the "pause_until" field.
func (_u *CredentialQuotaScopeUpdate) SetPauseUntil(v time.Time) *CredentialQuotaScopeUpdate {
	_u.mutation.SetPauseUntil(v)
	return _u
}

// SetNillablePauseUntil sets the "pause_until" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillablePauseUntil(v *time.Time) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetPauseUntil(*v)
	}
	return _u
}

// ClearPauseUntil clears the value of the "pause_until" field.
func (_u *CredentialQuotaScopeUpdate) ClearPauseUntil() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearPauseUntil()
	return _u
}

// SetSource sets the "source" field.
func (_u *CredentialQuotaScopeUpdate) SetSource(v credentialquotascope.Source) *CredentialQuotaScopeUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableSource(v *credentialquotascope.Source) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CredentialQuotaScopeUpdate) SetLastError(v string) *CredentialQuotaScopeUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableLastError(v *string) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CredentialQuotaScopeUpdate) ClearLastError() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *CredentialQuotaScopeUpdate) SetRemark(v string) *CredentialQuotaScopeUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdate) SetNillableRemark(v *string) *CredentialQuotaScopeUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *CredentialQuotaScopeUpdate) ClearRemark() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// AddCredentialIDs adds the "credentials" edge to the UpstreamCredential entity by IDs.
func (_u *CredentialQuotaScopeUpdate) AddCredentialIDs(ids ...int) *CredentialQuotaScopeUpdate {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the UpstreamCredential entity.
func (_u *CredentialQuotaScopeUpdate) AddCredentials(v ...*UpstreamCredential) *CredentialQuotaScopeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the RequestExecution entity by IDs.
func (_u *CredentialQuotaScopeUpdate) AddExecutionIDs(ids ...int) *CredentialQuotaScopeUpdate {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the RequestExecution entity.
func (_u *CredentialQuotaScopeUpdate) AddExecutions(v ...*RequestExecution) *CredentialQuotaScopeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *CredentialQuotaScopeUpdate) AddUsageLogIDs(ids ...int) *CredentialQuotaScopeUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *CredentialQuotaScopeUpdate) AddUsageLogs(v ...*UsageLog) *CredentialQuotaScopeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the CredentialQuotaScopeMutation object of the builder.
func (_u *CredentialQuotaScopeUpdate) Mutation() *CredentialQuotaScopeMutation {
	return _u.mutation
}

// ClearCredentials clears all "credentials" edges to the UpstreamCredential entity.
func (_u *CredentialQuotaScopeUpdate) ClearCredentials() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to UpstreamCredential entities by IDs.
func (_u *CredentialQuotaScopeUpdate) RemoveCredentialIDs(ids ...int) *CredentialQuotaScopeUpdate {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to UpstreamCredential entities.
func (_u *CredentialQuotaScopeUpdate) RemoveCredentials(v ...*UpstreamCredential) *CredentialQuotaScopeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// ClearExecutions clears all "executions" edges to the RequestExecution entity.
func (_u *CredentialQuotaScopeUpdate) ClearExecutions() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to RequestExecution entities by IDs.
func (_u *CredentialQuotaScopeUpdate) RemoveExecutionIDs(ids ...int) *CredentialQuotaScopeUpdate {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to RequestExecution entities.
func (_u *CredentialQuotaScopeUpdate) RemoveExecutions(v ...*RequestExecution) *CredentialQuotaScopeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *CredentialQuotaScopeUpdate) ClearUsageLogs() *CredentialQuotaScopeUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *CredentialQuotaScopeUpdate) RemoveUsageLogIDs(ids ...int) *CredentialQuotaScopeUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *CredentialQuotaScopeUpdate) RemoveUsageLogs(v ...*UsageLog) *CredentialQuotaScopeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialQuotaScopeUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialQuotaScopeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialQuotaScopeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialQuotaScopeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialQuotaScopeUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if credentialquotascope.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized credentialquotascope.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := credentialquotascope.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialQuotaScopeUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := credentialquotascope.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Unit(); ok {
		if err := credentialquotascope.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResetPolicy(); ok {
		if err := credentialquotascope.ResetPolicyValidator(v); err != nil {
			return &ValidationError{Name: "reset_policy", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.reset_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OverLimitAction(); ok {
		if err := credentialquotascope.OverLimitActionValidator(v); err != nil {
			return &ValidationError{Name: "over_limit_action", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.over_limit_action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := credentialquotascope.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.source": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CredentialQuotaScopeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CredentialQuotaScopeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CredentialQuotaScopeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialquotascope.Table, credentialquotascope.Columns, sqlgraph.NewFieldSpec(credentialquotascope.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialquotascope.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(credentialquotascope.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(credentialquotascope.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credentialquotascope.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(credentialquotascope.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(credentialquotascope.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(credentialquotascope.FieldUnit, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LimitAmount(); ok {
		_spec.SetField(credentialquotascope.FieldLimitAmount, field.TypeString, value)
	}
	if _u.mutation.LimitAmountCleared() {
		_spec.ClearField(credentialquotascope.FieldLimitAmount, field.TypeString)
	}
	if value, ok := _u.mutation.UsedAmount(); ok {
		_spec.SetField(credentialquotascope.FieldUsedAmount, field.TypeString, value)
	}
	if _u.mutation.UsedAmountCleared() {
		_spec.ClearField(credentialquotascope.FieldUsedAmount, field.TypeString)
	}
	if value, ok := _u.mutation.WarningThresholdPercent(); ok {
		_spec.SetField(credentialquotascope.FieldWarningThresholdPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWarningThresholdPercent(); ok {
		_spec.AddField(credentialquotascope.FieldWarningThresholdPercent, field.TypeInt, value)
	}
	if _u.mutation.WarningThresholdPercentCleared() {
		_spec.ClearField(credentialquotascope.FieldWarningThresholdPercent, field.TypeInt)
	}
	if value, ok := _u.mutation.ResetPolicy(); ok {
		_spec.SetField(credentialquotascope.FieldResetPolicy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(credentialquotascope.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(credentialquotascope.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WindowStartedAt(); ok {
		_spec.SetField(credentialquotascope.FieldWindowStartedAt, field.TypeTime, value)
	}
	if _u.mutation.WindowStartedAtCleared() {
		_spec.ClearField(credentialquotascope.FieldWindowStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OverLimitAction(); ok {
		_spec.SetField(credentialquotascope.FieldOverLimitAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PauseUntil(); ok {
		_spec.SetField(credentialquotascope.FieldPauseUntil, field.TypeTime, value)
	}
	if _u.mutation.PauseUntilCleared() {
		_spec.ClearField(credentialquotascope.FieldPauseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(credentialquotascope.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(credentialquotascope.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(credentialquotascope.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(credentialquotascope.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(credentialquotascope.FieldRemark, field.TypeString)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.CredentialsTable,
			Columns: []string{credentialquotascope.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.CredentialsTable,
			Columns: []string{credentialquotascope.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.CredentialsTable,
			Columns: []string{credentialquotascope.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.ExecutionsTable,
			Columns: []string{credentialquotascope.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.ExecutionsTable,
			Columns: []string{credentialquotascope.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.ExecutionsTable,
			Columns: []string{credentialquotascope.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.UsageLogsTable,
			Columns: []string{credentialquotascope.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.UsageLogsTable,
			Columns: []string{credentialquotascope.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.UsageLogsTable,
			Columns: []string{credentialquotascope.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialquotascope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialQuotaScopeUpdateOne is the builder for updating a single CredentialQuotaScope entity.
type CredentialQuotaScopeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CredentialQuotaScopeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialQuotaScopeUpdateOne) SetUpdatedAt(v time.Time) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CredentialQuotaScopeUpdateOne) SetDeletedAt(v int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableDeletedAt(v *int) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *CredentialQuotaScopeUpdateOne) AddDeletedAt(v int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CredentialQuotaScopeUpdateOne) SetName(v string) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableName(v *string) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearName() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CredentialQuotaScopeUpdateOne) SetStatus(v credentialquotascope.Status) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableStatus(v *credentialquotascope.Status) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUnit sets the "unit" field.
func (_u *CredentialQuotaScopeUpdateOne) SetUnit(v credentialquotascope.Unit) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetUnit(v)
	return _u
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableUnit(v *credentialquotascope.Unit) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetUnit(*v)
	}
	return _u
}

// SetLimitAmount sets the "limit_amount" field.
func (_u *CredentialQuotaScopeUpdateOne) SetLimitAmount(v string) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetLimitAmount(v)
	return _u
}

// SetNillableLimitAmount sets the "limit_amount" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableLimitAmount(v *string) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetLimitAmount(*v)
	}
	return _u
}

// ClearLimitAmount clears the value of the "limit_amount" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearLimitAmount() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearLimitAmount()
	return _u
}

// SetUsedAmount sets the "used_amount" field.
func (_u *CredentialQuotaScopeUpdateOne) SetUsedAmount(v string) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetUsedAmount(v)
	return _u
}

// SetNillableUsedAmount sets the "used_amount" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableUsedAmount(v *string) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetUsedAmount(*v)
	}
	return _u
}

// ClearUsedAmount clears the value of the "used_amount" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearUsedAmount() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearUsedAmount()
	return _u
}

// SetWarningThresholdPercent sets the "warning_threshold_percent" field.
func (_u *CredentialQuotaScopeUpdateOne) SetWarningThresholdPercent(v int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.ResetWarningThresholdPercent()
	_u.mutation.SetWarningThresholdPercent(v)
	return _u
}

// SetNillableWarningThresholdPercent sets the "warning_threshold_percent" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableWarningThresholdPercent(v *int) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetWarningThresholdPercent(*v)
	}
	return _u
}

// AddWarningThresholdPercent adds value to the "warning_threshold_percent" field.
func (_u *CredentialQuotaScopeUpdateOne) AddWarningThresholdPercent(v int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.AddWarningThresholdPercent(v)
	return _u
}

// ClearWarningThresholdPercent clears the value of the "warning_threshold_percent" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearWarningThresholdPercent() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearWarningThresholdPercent()
	return _u
}

// SetResetPolicy sets the "reset_policy" field.
func (_u *CredentialQuotaScopeUpdateOne) SetResetPolicy(v credentialquotascope.ResetPolicy) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetResetPolicy(v)
	return _u
}

// SetNillableResetPolicy sets the "reset_policy" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableResetPolicy(v *credentialquotascope.ResetPolicy) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetResetPolicy(*v)
	}
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *CredentialQuotaScopeUpdateOne) SetResetAt(v time.Time) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableResetAt(v *time.Time) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearResetAt() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearResetAt()
	return _u
}

// SetWindowStartedAt sets the "window_started_at" field.
func (_u *CredentialQuotaScopeUpdateOne) SetWindowStartedAt(v time.Time) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetWindowStartedAt(v)
	return _u
}

// SetNillableWindowStartedAt sets the "window_started_at" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableWindowStartedAt(v *time.Time) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetWindowStartedAt(*v)
	}
	return _u
}

// ClearWindowStartedAt clears the value of the "window_started_at" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearWindowStartedAt() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearWindowStartedAt()
	return _u
}

// SetOverLimitAction sets the "over_limit_action" field.
func (_u *CredentialQuotaScopeUpdateOne) SetOverLimitAction(v credentialquotascope.OverLimitAction) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetOverLimitAction(v)
	return _u
}

// SetNillableOverLimitAction sets the "over_limit_action" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableOverLimitAction(v *credentialquotascope.OverLimitAction) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetOverLimitAction(*v)
	}
	return _u
}

// SetPauseUntil sets the "pause_until" field.
func (_u *CredentialQuotaScopeUpdateOne) SetPauseUntil(v time.Time) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetPauseUntil(v)
	return _u
}

// SetNillablePauseUntil sets the "pause_until" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillablePauseUntil(v *time.Time) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetPauseUntil(*v)
	}
	return _u
}

// ClearPauseUntil clears the value of the "pause_until" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearPauseUntil() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearPauseUntil()
	return _u
}

// SetSource sets the "source" field.
func (_u *CredentialQuotaScopeUpdateOne) SetSource(v credentialquotascope.Source) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableSource(v *credentialquotascope.Source) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CredentialQuotaScopeUpdateOne) SetLastError(v string) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableLastError(v *string) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearLastError() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *CredentialQuotaScopeUpdateOne) SetRemark(v string) *CredentialQuotaScopeUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *CredentialQuotaScopeUpdateOne) SetNillableRemark(v *string) *CredentialQuotaScopeUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *CredentialQuotaScopeUpdateOne) ClearRemark() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// AddCredentialIDs adds the "credentials" edge to the UpstreamCredential entity by IDs.
func (_u *CredentialQuotaScopeUpdateOne) AddCredentialIDs(ids ...int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the UpstreamCredential entity.
func (_u *CredentialQuotaScopeUpdateOne) AddCredentials(v ...*UpstreamCredential) *CredentialQuotaScopeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the RequestExecution entity by IDs.
func (_u *CredentialQuotaScopeUpdateOne) AddExecutionIDs(ids ...int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the RequestExecution entity.
func (_u *CredentialQuotaScopeUpdateOne) AddExecutions(v ...*RequestExecution) *CredentialQuotaScopeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *CredentialQuotaScopeUpdateOne) AddUsageLogIDs(ids ...int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *CredentialQuotaScopeUpdateOne) AddUsageLogs(v ...*UsageLog) *CredentialQuotaScopeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the CredentialQuotaScopeMutation object of the builder.
func (_u *CredentialQuotaScopeUpdateOne) Mutation() *CredentialQuotaScopeMutation {
	return _u.mutation
}

// ClearCredentials clears all "credentials" edges to the UpstreamCredential entity.
func (_u *CredentialQuotaScopeUpdateOne) ClearCredentials() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to UpstreamCredential entities by IDs.
func (_u *CredentialQuotaScopeUpdateOne) RemoveCredentialIDs(ids ...int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to UpstreamCredential entities.
func (_u *CredentialQuotaScopeUpdateOne) RemoveCredentials(v ...*UpstreamCredential) *CredentialQuotaScopeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// ClearExecutions clears all "executions" edges to the RequestExecution entity.
func (_u *CredentialQuotaScopeUpdateOne) ClearExecutions() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to RequestExecution entities by IDs.
func (_u *CredentialQuotaScopeUpdateOne) RemoveExecutionIDs(ids ...int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to RequestExecution entities.
func (_u *CredentialQuotaScopeUpdateOne) RemoveExecutions(v ...*RequestExecution) *CredentialQuotaScopeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *CredentialQuotaScopeUpdateOne) ClearUsageLogs() *CredentialQuotaScopeUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *CredentialQuotaScopeUpdateOne) RemoveUsageLogIDs(ids ...int) *CredentialQuotaScopeUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *CredentialQuotaScopeUpdateOne) RemoveUsageLogs(v ...*UsageLog) *CredentialQuotaScopeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the CredentialQuotaScopeUpdate builder.
func (_u *CredentialQuotaScopeUpdateOne) Where(ps ...predicate.CredentialQuotaScope) *CredentialQuotaScopeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialQuotaScopeUpdateOne) Select(field string, fields ...string) *CredentialQuotaScopeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CredentialQuotaScope entity.
func (_u *CredentialQuotaScopeUpdateOne) Save(ctx context.Context) (*CredentialQuotaScope, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialQuotaScopeUpdateOne) SaveX(ctx context.Context) *CredentialQuotaScope {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialQuotaScopeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialQuotaScopeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialQuotaScopeUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if credentialquotascope.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized credentialquotascope.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := credentialquotascope.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialQuotaScopeUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := credentialquotascope.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Unit(); ok {
		if err := credentialquotascope.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResetPolicy(); ok {
		if err := credentialquotascope.ResetPolicyValidator(v); err != nil {
			return &ValidationError{Name: "reset_policy", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.reset_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OverLimitAction(); ok {
		if err := credentialquotascope.OverLimitActionValidator(v); err != nil {
			return &ValidationError{Name: "over_limit_action", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.over_limit_action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := credentialquotascope.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CredentialQuotaScope.source": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CredentialQuotaScopeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CredentialQuotaScopeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CredentialQuotaScopeUpdateOne) sqlSave(ctx context.Context) (_node *CredentialQuotaScope, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialquotascope.Table, credentialquotascope.Columns, sqlgraph.NewFieldSpec(credentialquotascope.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CredentialQuotaScope.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credentialquotascope.FieldID)
		for _, f := range fields {
			if !credentialquotascope.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credentialquotascope.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialquotascope.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(credentialquotascope.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(credentialquotascope.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credentialquotascope.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(credentialquotascope.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(credentialquotascope.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Unit(); ok {
		_spec.SetField(credentialquotascope.FieldUnit, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LimitAmount(); ok {
		_spec.SetField(credentialquotascope.FieldLimitAmount, field.TypeString, value)
	}
	if _u.mutation.LimitAmountCleared() {
		_spec.ClearField(credentialquotascope.FieldLimitAmount, field.TypeString)
	}
	if value, ok := _u.mutation.UsedAmount(); ok {
		_spec.SetField(credentialquotascope.FieldUsedAmount, field.TypeString, value)
	}
	if _u.mutation.UsedAmountCleared() {
		_spec.ClearField(credentialquotascope.FieldUsedAmount, field.TypeString)
	}
	if value, ok := _u.mutation.WarningThresholdPercent(); ok {
		_spec.SetField(credentialquotascope.FieldWarningThresholdPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWarningThresholdPercent(); ok {
		_spec.AddField(credentialquotascope.FieldWarningThresholdPercent, field.TypeInt, value)
	}
	if _u.mutation.WarningThresholdPercentCleared() {
		_spec.ClearField(credentialquotascope.FieldWarningThresholdPercent, field.TypeInt)
	}
	if value, ok := _u.mutation.ResetPolicy(); ok {
		_spec.SetField(credentialquotascope.FieldResetPolicy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(credentialquotascope.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(credentialquotascope.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WindowStartedAt(); ok {
		_spec.SetField(credentialquotascope.FieldWindowStartedAt, field.TypeTime, value)
	}
	if _u.mutation.WindowStartedAtCleared() {
		_spec.ClearField(credentialquotascope.FieldWindowStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OverLimitAction(); ok {
		_spec.SetField(credentialquotascope.FieldOverLimitAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PauseUntil(); ok {
		_spec.SetField(credentialquotascope.FieldPauseUntil, field.TypeTime, value)
	}
	if _u.mutation.PauseUntilCleared() {
		_spec.ClearField(credentialquotascope.FieldPauseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(credentialquotascope.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(credentialquotascope.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(credentialquotascope.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(credentialquotascope.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(credentialquotascope.FieldRemark, field.TypeString)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.CredentialsTable,
			Columns: []string{credentialquotascope.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.CredentialsTable,
			Columns: []string{credentialquotascope.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.CredentialsTable,
			Columns: []string{credentialquotascope.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.ExecutionsTable,
			Columns: []string{credentialquotascope.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.ExecutionsTable,
			Columns: []string{credentialquotascope.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.ExecutionsTable,
			Columns: []string{credentialquotascope.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.UsageLogsTable,
			Columns: []string{credentialquotascope.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.UsageLogsTable,
			Columns: []string{credentialquotascope.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialquotascope.UsageLogsTable,
			Columns: []string{credentialquotascope.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CredentialQuotaScope{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialquotascope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
