// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/credentialquotascope"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/providerquotastatus"
	"github.com/looplj/axonhub/internal/ent/upstreamcredential"
)

// ProviderQuotaStatusUpdate is the builder for updating ProviderQuotaStatus entities.
type ProviderQuotaStatusUpdate struct {
	config
	hooks     []Hook
	mutation  *ProviderQuotaStatusMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProviderQuotaStatusUpdate builder.
func (_u *ProviderQuotaStatusUpdate) Where(ps ...predicate.ProviderQuotaStatus) *ProviderQuotaStatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderQuotaStatusUpdate) SetUpdatedAt(v time.Time) *ProviderQuotaStatusUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProviderQuotaStatusUpdate) SetDeletedAt(v int) *ProviderQuotaStatusUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableDeletedAt(v *int) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ProviderQuotaStatusUpdate) AddDeletedAt(v int) *ProviderQuotaStatusUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ProviderQuotaStatusUpdate) SetChannelID(v int) *ProviderQuotaStatusUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableChannelID(v *int) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *ProviderQuotaStatusUpdate) ClearChannelID() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetScopeKey sets the "scope_key" field.
func (_u *ProviderQuotaStatusUpdate) SetScopeKey(v string) *ProviderQuotaStatusUpdate {
	_u.mutation.SetScopeKey(v)
	return _u
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableScopeKey(v *string) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetScopeKey(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *ProviderQuotaStatusUpdate) SetCredentialID(v int) *ProviderQuotaStatusUpdate {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableCredentialID(v *int) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// ClearCredentialID clears the value of the "credential_id" field.
func (_u *ProviderQuotaStatusUpdate) ClearCredentialID() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearCredentialID()
	return _u
}

// SetCredentialFingerprint sets the "credential_fingerprint" field.
func (_u *ProviderQuotaStatusUpdate) SetCredentialFingerprint(v string) *ProviderQuotaStatusUpdate {
	_u.mutation.SetCredentialFingerprint(v)
	return _u
}

// SetNillableCredentialFingerprint sets the "credential_fingerprint" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableCredentialFingerprint(v *string) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetCredentialFingerprint(*v)
	}
	return _u
}

// ClearCredentialFingerprint clears the value of the "credential_fingerprint" field.
func (_u *ProviderQuotaStatusUpdate) ClearCredentialFingerprint() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearCredentialFingerprint()
	return _u
}

// SetSecretFingerprint sets the "secret_fingerprint" field.
func (_u *ProviderQuotaStatusUpdate) SetSecretFingerprint(v string) *ProviderQuotaStatusUpdate {
	_u.mutation.SetSecretFingerprint(v)
	return _u
}

// SetNillableSecretFingerprint sets the "secret_fingerprint" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableSecretFingerprint(v *string) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetSecretFingerprint(*v)
	}
	return _u
}

// ClearSecretFingerprint clears the value of the "secret_fingerprint" field.
func (_u *ProviderQuotaStatusUpdate) ClearSecretFingerprint() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearSecretFingerprint()
	return _u
}

// SetResourceScopeKey sets the "resource_scope_key" field.
func (_u *ProviderQuotaStatusUpdate) SetResourceScopeKey(v string) *ProviderQuotaStatusUpdate {
	_u.mutation.SetResourceScopeKey(v)
	return _u
}

// SetNillableResourceScopeKey sets the "resource_scope_key" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableResourceScopeKey(v *string) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetResourceScopeKey(*v)
	}
	return _u
}

// ClearResourceScopeKey clears the value of the "resource_scope_key" field.
func (_u *ProviderQuotaStatusUpdate) ClearResourceScopeKey() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearResourceScopeKey()
	return _u
}

// SetQuotaScopeID sets the "quota_scope_id" field.
func (_u *ProviderQuotaStatusUpdate) SetQuotaScopeID(v int) *ProviderQuotaStatusUpdate {
	_u.mutation.SetQuotaScopeID(v)
	return _u
}

// SetNillableQuotaScopeID sets the "quota_scope_id" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableQuotaScopeID(v *int) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetQuotaScopeID(*v)
	}
	return _u
}

// ClearQuotaScopeID clears the value of the "quota_scope_id" field.
func (_u *ProviderQuotaStatusUpdate) ClearQuotaScopeID() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearQuotaScopeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderQuotaStatusUpdate) SetStatus(v providerquotastatus.Status) *ProviderQuotaStatusUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableStatus(v *providerquotastatus.Status) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaData sets the "quota_data" field.
func (_u *ProviderQuotaStatusUpdate) SetQuotaData(v map[string]interface{}) *ProviderQuotaStatusUpdate {
	_u.mutation.SetQuotaData(v)
	return _u
}

// SetNextResetAt sets the "next_reset_at" field.
func (_u *ProviderQuotaStatusUpdate) SetNextResetAt(v time.Time) *ProviderQuotaStatusUpdate {
	_u.mutation.SetNextResetAt(v)
	return _u
}

// SetNillableNextResetAt sets the "next_reset_at" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableNextResetAt(v *time.Time) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetNextResetAt(*v)
	}
	return _u
}

// ClearNextResetAt clears the value of the "next_reset_at" field.
func (_u *ProviderQuotaStatusUpdate) ClearNextResetAt() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearNextResetAt()
	return _u
}

// SetReady sets the "ready" field.
func (_u *ProviderQuotaStatusUpdate) SetReady(v bool) *ProviderQuotaStatusUpdate {
	_u.mutation.SetReady(v)
	return _u
}

// SetNillableReady sets the "ready" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableReady(v *bool) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetReady(*v)
	}
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *ProviderQuotaStatusUpdate) SetNextCheckAt(v time.Time) *ProviderQuotaStatusUpdate {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdate) SetNillableNextCheckAt(v *time.Time) *ProviderQuotaStatusUpdate {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ProviderQuotaStatusUpdate) SetChannel(v *Channel) *ProviderQuotaStatusUpdate {
	return _u.SetChannelID(v.ID)
}

// SetCredential sets the "credential" edge to the UpstreamCredential entity.
func (_u *ProviderQuotaStatusUpdate) SetCredential(v *UpstreamCredential) *ProviderQuotaStatusUpdate {
	return _u.SetCredentialID(v.ID)
}

// SetQuotaScope sets the "quota_scope" edge to the CredentialQuotaScope entity.
func (_u *ProviderQuotaStatusUpdate) SetQuotaScope(v *CredentialQuotaScope) *ProviderQuotaStatusUpdate {
	return _u.SetQuotaScopeID(v.ID)
}

// Mutation returns the ProviderQuotaStatusMutation object of the builder.
func (_u *ProviderQuotaStatusUpdate) Mutation() *ProviderQuotaStatusMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ProviderQuotaStatusUpdate) ClearChannel() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearCredential clears the "credential" edge to the UpstreamCredential entity.
func (_u *ProviderQuotaStatusUpdate) ClearCredential() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearCredential()
	return _u
}

// ClearQuotaScope clears the "quota_scope" edge to the CredentialQuotaScope entity.
func (_u *ProviderQuotaStatusUpdate) ClearQuotaScope() *ProviderQuotaStatusUpdate {
	_u.mutation.ClearQuotaScope()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderQuotaStatusUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderQuotaStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderQuotaStatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderQuotaStatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderQuotaStatusUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if providerquotastatus.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized providerquotastatus.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := providerquotastatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderQuotaStatusUpdate) check() error {
	if v, ok := _u.mutation.ScopeKey(); ok {
		if err := providerquotastatus.ScopeKeyValidator(v); err != nil {
			return &ValidationError{Name: "scope_key", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.scope_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialFingerprint(); ok {
		if err := providerquotastatus.CredentialFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "credential_fingerprint", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.credential_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretFingerprint(); ok {
		if err := providerquotastatus.SecretFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "secret_fingerprint", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.secret_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceScopeKey(); ok {
		if err := providerquotastatus.ResourceScopeKeyValidator(v); err != nil {
			return &ValidationError{Name: "resource_scope_key", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.resource_scope_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := providerquotastatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProviderQuotaStatusUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProviderQuotaStatusUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProviderQuotaStatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerquotastatus.Table, providerquotastatus.Columns, sqlgraph.NewFieldSpec(providerquotastatus.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerquotastatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(providerquotastatus.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(providerquotastatus.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScopeKey(); ok {
		_spec.SetField(providerquotastatus.FieldScopeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialFingerprint(); ok {
		_spec.SetField(providerquotastatus.FieldCredentialFingerprint, field.TypeString, value)
	}
	if _u.mutation.CredentialFingerprintCleared() {
		_spec.ClearField(providerquotastatus.FieldCredentialFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.SecretFingerprint(); ok {
		_spec.SetField(providerquotastatus.FieldSecretFingerprint, field.TypeString, value)
	}
	if _u.mutation.SecretFingerprintCleared() {
		_spec.ClearField(providerquotastatus.FieldSecretFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceScopeKey(); ok {
		_spec.SetField(providerquotastatus.FieldResourceScopeKey, field.TypeString, value)
	}
	if _u.mutation.ResourceScopeKeyCleared() {
		_spec.ClearField(providerquotastatus.FieldResourceScopeKey, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providerquotastatus.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuotaData(); ok {
		_spec.SetField(providerquotastatus.FieldQuotaData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.NextResetAt(); ok {
		_spec.SetField(providerquotastatus.FieldNextResetAt, field.TypeTime, value)
	}
	if _u.mutation.NextResetAtCleared() {
		_spec.ClearField(providerquotastatus.FieldNextResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Ready(); ok {
		_spec.SetField(providerquotastatus.FieldReady, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(providerquotastatus.FieldNextCheckAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.ChannelTable,
			Columns: []string{providerquotastatus.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.ChannelTable,
			Columns: []string{providerquotastatus.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.CredentialTable,
			Columns: []string{providerquotastatus.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.CredentialTable,
			Columns: []string{providerquotastatus.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuotaScopeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.QuotaScopeTable,
			Columns: []string{providerquotastatus.QuotaScopeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialquotascope.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuotaScopeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.QuotaScopeTable,
			Columns: []string{providerquotastatus.QuotaScopeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialquotascope.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerquotastatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderQuotaStatusUpdateOne is the builder for updating a single ProviderQuotaStatus entity.
type ProviderQuotaStatusUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProviderQuotaStatusMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderQuotaStatusUpdateOne) SetUpdatedAt(v time.Time) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProviderQuotaStatusUpdateOne) SetDeletedAt(v int) *ProviderQuotaStatusUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableDeletedAt(v *int) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ProviderQuotaStatusUpdateOne) AddDeletedAt(v int) *ProviderQuotaStatusUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ProviderQuotaStatusUpdateOne) SetChannelID(v int) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableChannelID(v *int) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *ProviderQuotaStatusUpdateOne) ClearChannelID() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetScopeKey sets the "scope_key" field.
func (_u *ProviderQuotaStatusUpdateOne) SetScopeKey(v string) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetScopeKey(v)
	return _u
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableScopeKey(v *string) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetScopeKey(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *ProviderQuotaStatusUpdateOne) SetCredentialID(v int) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableCredentialID(v *int) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// ClearCredentialID clears the value of the "credential_id" field.
func (_u *ProviderQuotaStatusUpdateOne) ClearCredentialID() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearCredentialID()
	return _u
}

// SetCredentialFingerprint sets the "credential_fingerprint" field.
func (_u *ProviderQuotaStatusUpdateOne) SetCredentialFingerprint(v string) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetCredentialFingerprint(v)
	return _u
}

// SetNillableCredentialFingerprint sets the "credential_fingerprint" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableCredentialFingerprint(v *string) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetCredentialFingerprint(*v)
	}
	return _u
}

// ClearCredentialFingerprint clears the value of the "credential_fingerprint" field.
func (_u *ProviderQuotaStatusUpdateOne) ClearCredentialFingerprint() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearCredentialFingerprint()
	return _u
}

// SetSecretFingerprint sets the "secret_fingerprint" field.
func (_u *ProviderQuotaStatusUpdateOne) SetSecretFingerprint(v string) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetSecretFingerprint(v)
	return _u
}

// SetNillableSecretFingerprint sets the "secret_fingerprint" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableSecretFingerprint(v *string) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetSecretFingerprint(*v)
	}
	return _u
}

// ClearSecretFingerprint clears the value of the "secret_fingerprint" field.
func (_u *ProviderQuotaStatusUpdateOne) ClearSecretFingerprint() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearSecretFingerprint()
	return _u
}

// SetResourceScopeKey sets the "resource_scope_key" field.
func (_u *ProviderQuotaStatusUpdateOne) SetResourceScopeKey(v string) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetResourceScopeKey(v)
	return _u
}

// SetNillableResourceScopeKey sets the "resource_scope_key" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableResourceScopeKey(v *string) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetResourceScopeKey(*v)
	}
	return _u
}

// ClearResourceScopeKey clears the value of the "resource_scope_key" field.
func (_u *ProviderQuotaStatusUpdateOne) ClearResourceScopeKey() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearResourceScopeKey()
	return _u
}

// SetQuotaScopeID sets the "quota_scope_id" field.
func (_u *ProviderQuotaStatusUpdateOne) SetQuotaScopeID(v int) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetQuotaScopeID(v)
	return _u
}

// SetNillableQuotaScopeID sets the "quota_scope_id" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableQuotaScopeID(v *int) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetQuotaScopeID(*v)
	}
	return _u
}

// ClearQuotaScopeID clears the value of the "quota_scope_id" field.
func (_u *ProviderQuotaStatusUpdateOne) ClearQuotaScopeID() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearQuotaScopeID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderQuotaStatusUpdateOne) SetStatus(v providerquotastatus.Status) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableStatus(v *providerquotastatus.Status) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetQuotaData sets the "quota_data" field.
func (_u *ProviderQuotaStatusUpdateOne) SetQuotaData(v map[string]interface{}) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetQuotaData(v)
	return _u
}

// SetNextResetAt sets the "next_reset_at" field.
func (_u *ProviderQuotaStatusUpdateOne) SetNextResetAt(v time.Time) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetNextResetAt(v)
	return _u
}

// SetNillableNextResetAt sets the "next_reset_at" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableNextResetAt(v *time.Time) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetNextResetAt(*v)
	}
	return _u
}

// ClearNextResetAt clears the value of the "next_reset_at" field.
func (_u *ProviderQuotaStatusUpdateOne) ClearNextResetAt() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearNextResetAt()
	return _u
}

// SetReady sets the "ready" field.
func (_u *ProviderQuotaStatusUpdateOne) SetReady(v bool) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetReady(v)
	return _u
}

// SetNillableReady sets the "ready" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableReady(v *bool) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetReady(*v)
	}
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *ProviderQuotaStatusUpdateOne) SetNextCheckAt(v time.Time) *ProviderQuotaStatusUpdateOne {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *ProviderQuotaStatusUpdateOne) SetNillableNextCheckAt(v *time.Time) *ProviderQuotaStatusUpdateOne {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ProviderQuotaStatusUpdateOne) SetChannel(v *Channel) *ProviderQuotaStatusUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetCredential sets the "credential" edge to the UpstreamCredential entity.
func (_u *ProviderQuotaStatusUpdateOne) SetCredential(v *UpstreamCredential) *ProviderQuotaStatusUpdateOne {
	return _u.SetCredentialID(v.ID)
}

// SetQuotaScope sets the "quota_scope" edge to the CredentialQuotaScope entity.
func (_u *ProviderQuotaStatusUpdateOne) SetQuotaScope(v *CredentialQuotaScope) *ProviderQuotaStatusUpdateOne {
	return _u.SetQuotaScopeID(v.ID)
}

// Mutation returns the ProviderQuotaStatusMutation object of the builder.
func (_u *ProviderQuotaStatusUpdateOne) Mutation() *ProviderQuotaStatusMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ProviderQuotaStatusUpdateOne) ClearChannel() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearCredential clears the "credential" edge to the UpstreamCredential entity.
func (_u *ProviderQuotaStatusUpdateOne) ClearCredential() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearCredential()
	return _u
}

// ClearQuotaScope clears the "quota_scope" edge to the CredentialQuotaScope entity.
func (_u *ProviderQuotaStatusUpdateOne) ClearQuotaScope() *ProviderQuotaStatusUpdateOne {
	_u.mutation.ClearQuotaScope()
	return _u
}

// Where appends a list predicates to the ProviderQuotaStatusUpdate builder.
func (_u *ProviderQuotaStatusUpdateOne) Where(ps ...predicate.ProviderQuotaStatus) *ProviderQuotaStatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderQuotaStatusUpdateOne) Select(field string, fields ...string) *ProviderQuotaStatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderQuotaStatus entity.
func (_u *ProviderQuotaStatusUpdateOne) Save(ctx context.Context) (*ProviderQuotaStatus, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderQuotaStatusUpdateOne) SaveX(ctx context.Context) *ProviderQuotaStatus {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderQuotaStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderQuotaStatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderQuotaStatusUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if providerquotastatus.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized providerquotastatus.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := providerquotastatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderQuotaStatusUpdateOne) check() error {
	if v, ok := _u.mutation.ScopeKey(); ok {
		if err := providerquotastatus.ScopeKeyValidator(v); err != nil {
			return &ValidationError{Name: "scope_key", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.scope_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialFingerprint(); ok {
		if err := providerquotastatus.CredentialFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "credential_fingerprint", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.credential_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretFingerprint(); ok {
		if err := providerquotastatus.SecretFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "secret_fingerprint", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.secret_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceScopeKey(); ok {
		if err := providerquotastatus.ResourceScopeKeyValidator(v); err != nil {
			return &ValidationError{Name: "resource_scope_key", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.resource_scope_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := providerquotastatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderQuotaStatus.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProviderQuotaStatusUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProviderQuotaStatusUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProviderQuotaStatusUpdateOne) sqlSave(ctx context.Context) (_node *ProviderQuotaStatus, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerquotastatus.Table, providerquotastatus.Columns, sqlgraph.NewFieldSpec(providerquotastatus.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderQuotaStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerquotastatus.FieldID)
		for _, f := range fields {
			if !providerquotastatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerquotastatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerquotastatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(providerquotastatus.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(providerquotastatus.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ScopeKey(); ok {
		_spec.SetField(providerquotastatus.FieldScopeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialFingerprint(); ok {
		_spec.SetField(providerquotastatus.FieldCredentialFingerprint, field.TypeString, value)
	}
	if _u.mutation.CredentialFingerprintCleared() {
		_spec.ClearField(providerquotastatus.FieldCredentialFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.SecretFingerprint(); ok {
		_spec.SetField(providerquotastatus.FieldSecretFingerprint, field.TypeString, value)
	}
	if _u.mutation.SecretFingerprintCleared() {
		_spec.ClearField(providerquotastatus.FieldSecretFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceScopeKey(); ok {
		_spec.SetField(providerquotastatus.FieldResourceScopeKey, field.TypeString, value)
	}
	if _u.mutation.ResourceScopeKeyCleared() {
		_spec.ClearField(providerquotastatus.FieldResourceScopeKey, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providerquotastatus.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuotaData(); ok {
		_spec.SetField(providerquotastatus.FieldQuotaData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.NextResetAt(); ok {
		_spec.SetField(providerquotastatus.FieldNextResetAt, field.TypeTime, value)
	}
	if _u.mutation.NextResetAtCleared() {
		_spec.ClearField(providerquotastatus.FieldNextResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Ready(); ok {
		_spec.SetField(providerquotastatus.FieldReady, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(providerquotastatus.FieldNextCheckAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.ChannelTable,
			Columns: []string{providerquotastatus.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.ChannelTable,
			Columns: []string{providerquotastatus.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.CredentialTable,
			Columns: []string{providerquotastatus.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.CredentialTable,
			Columns: []string{providerquotastatus.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuotaScopeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.QuotaScopeTable,
			Columns: []string{providerquotastatus.QuotaScopeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialquotascope.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuotaScopeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   providerquotastatus.QuotaScopeTable,
			Columns: []string{providerquotastatus.QuotaScopeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialquotascope.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ProviderQuotaStatus{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerquotastatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
