// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/upstreamcredential"
	"github.com/looplj/axonhub/internal/objects"
)

// UpstreamCredential is the model entity for the UpstreamCredential schema.
type UpstreamCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Provider or channel type scope used to identify the upstream credential
	ProviderType string `json:"provider_type,omitempty"`
	// Normalized upstream base URL scope for this credential
	BaseURL string `json:"base_url,omitempty"`
	// AuthKind holds the value of the "auth_kind" field.
	AuthKind upstreamcredential.AuthKind `json:"auth_kind,omitempty"`
	// Internal secret kind for the upstream account asset; not a channel/API-format setting
	SecretKind upstreamcredential.SecretKind `json:"secret_kind,omitempty"`
	// Coarse upstream issuer namespace used for credential identity; not the channel base URL
	IssuerScope string `json:"issuer_scope,omitempty"`
	// Safe display hint for the secret; never contains the full secret
	KeyHint string `json:"key_hint,omitempty"`
	// Optional shared quota/billing scope for credentials that belong to one upstream account pool
	QuotaScopeID *int `json:"quota_scope_id,omitempty"`
	// SecretPayload holds the value of the "secret_payload" field.
	SecretPayload objects.UpstreamCredentialSecret `json:"-"`
	// Safe upstream credential identity; never contains raw secret material
	Fingerprint string `json:"fingerprint,omitempty"`
	// Status holds the value of the "status" field.
	Status upstreamcredential.Status `json:"status,omitempty"`
	// Default credential selection weight inside eligible channel refs
	Weight int `json:"weight,omitempty"`
	// Latest credential-scoped quota or budget status summary
	QuotaStatus string `json:"quota_status,omitempty"`
	// Latest credential-scoped error summary safe for operator display
	LastError string `json:"last_error,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamCredentialQuery when eager-loading is set.
	Edges        UpstreamCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamCredentialEdges holds the relations/edges for other nodes in the graph.
type UpstreamCredentialEdges struct {
	// ChannelRefs holds the value of the channel_refs edge.
	ChannelRefs []*ChannelCredentialRef `json:"channel_refs,omitempty"`
	// Executions holds the value of the executions edge.
	Executions []*RequestExecution `json:"executions,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// ProviderQuotaStatuses holds the value of the provider_quota_statuses edge.
	ProviderQuotaStatuses []*ProviderQuotaStatus `json:"provider_quota_statuses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int

	namedChannelRefs           map[string][]*ChannelCredentialRef
	namedExecutions            map[string][]*RequestExecution
	namedUsageLogs             map[string][]*UsageLog
	namedProviderQuotaStatuses map[string][]*ProviderQuotaStatus
}

// ChannelRefsOrErr returns the ChannelRefs value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamCredentialEdges) ChannelRefsOrErr() ([]*ChannelCredentialRef, error) {
	if e.loadedTypes[0] {
		return e.ChannelRefs, nil
	}
	return nil, &NotLoadedError{edge: "channel_refs"}
}

// ExecutionsOrErr returns the Executions value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamCredentialEdges) ExecutionsOrErr() ([]*RequestExecution, error) {
	if e.loadedTypes[1] {
		return e.Executions, nil
	}
	return nil, &NotLoadedError{edge: "executions"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamCredentialEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[2] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// ProviderQuotaStatusesOrErr returns the ProviderQuotaStatuses value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamCredentialEdges) ProviderQuotaStatusesOrErr() ([]*ProviderQuotaStatus, error) {
	if e.loadedTypes[3] {
		return e.ProviderQuotaStatuses, nil
	}
	return nil, &NotLoadedError{edge: "provider_quota_statuses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamcredential.FieldSecretPayload:
			values[i] = new([]byte)
		case upstreamcredential.FieldID, upstreamcredential.FieldDeletedAt, upstreamcredential.FieldQuotaScopeID, upstreamcredential.FieldWeight:
			values[i] = new(sql.NullInt64)
		case upstreamcredential.FieldName, upstreamcredential.FieldProviderType, upstreamcredential.FieldBaseURL, upstreamcredential.FieldAuthKind, upstreamcredential.FieldSecretKind, upstreamcredential.FieldIssuerScope, upstreamcredential.FieldKeyHint, upstreamcredential.FieldFingerprint, upstreamcredential.FieldStatus, upstreamcredential.FieldQuotaStatus, upstreamcredential.FieldLastError, upstreamcredential.FieldRemark:
			values[i] = new(sql.NullString)
		case upstreamcredential.FieldCreatedAt, upstreamcredential.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamCredential fields.
func (_m *UpstreamCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamcredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case upstreamcredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamcredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamcredential.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case upstreamcredential.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamcredential.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = value.String
			}
		case upstreamcredential.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstreamcredential.FieldAuthKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_kind", values[i])
			} else if value.Valid {
				_m.AuthKind = upstreamcredential.AuthKind(value.String)
			}
		case upstreamcredential.FieldSecretKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_kind", values[i])
			} else if value.Valid {
				_m.SecretKind = upstreamcredential.SecretKind(value.String)
			}
		case upstreamcredential.FieldIssuerScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer_scope", values[i])
			} else if value.Valid {
				_m.IssuerScope = value.String
			}
		case upstreamcredential.FieldKeyHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_hint", values[i])
			} else if value.Valid {
				_m.KeyHint = value.String
			}
		case upstreamcredential.FieldQuotaScopeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_scope_id", values[i])
			} else if value.Valid {
				_m.QuotaScopeID = new(int)
				*_m.QuotaScopeID = int(value.Int64)
			}
		case upstreamcredential.FieldSecretPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SecretPayload); err != nil {
					return fmt.Errorf("unmarshal field secret_payload: %w", err)
				}
			}
		case upstreamcredential.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case upstreamcredential.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = upstreamcredential.Status(value.String)
			}
		case upstreamcredential.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case upstreamcredential.FieldQuotaStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quota_status", values[i])
			} else if value.Valid {
				_m.QuotaStatus = value.String
			}
		case upstreamcredential.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case upstreamcredential.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamCredential.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannelRefs queries the "channel_refs" edge of the UpstreamCredential entity.
func (_m *UpstreamCredential) QueryChannelRefs() *ChannelCredentialRefQuery {
	return NewUpstreamCredentialClient(_m.config).QueryChannelRefs(_m)
}

// QueryExecutions queries the "executions" edge of the UpstreamCredential entity.
func (_m *UpstreamCredential) QueryExecutions() *RequestExecutionQuery {
	return NewUpstreamCredentialClient(_m.config).QueryExecutions(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the UpstreamCredential entity.
func (_m *UpstreamCredential) QueryUsageLogs() *UsageLogQuery {
	return NewUpstreamCredentialClient(_m.config).QueryUsageLogs(_m)
}

// QueryProviderQuotaStatuses queries the "provider_quota_statuses" edge of the UpstreamCredential entity.
func (_m *UpstreamCredential) QueryProviderQuotaStatuses() *ProviderQuotaStatusQuery {
	return NewUpstreamCredentialClient(_m.config).QueryProviderQuotaStatuses(_m)
}

// Update returns a builder for updating this UpstreamCredential.
// Note that you need to call UpstreamCredential.Unwrap() before calling this method if this UpstreamCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamCredential) Update() *UpstreamCredentialUpdateOne {
	return NewUpstreamCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamCredential) Unwrap() *UpstreamCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamCredential) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(_m.ProviderType)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("auth_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthKind))
	builder.WriteString(", ")
	builder.WriteString("secret_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.SecretKind))
	builder.WriteString(", ")
	builder.WriteString("issuer_scope=")
	builder.WriteString(_m.IssuerScope)
	builder.WriteString(", ")
	builder.WriteString("key_hint=")
	builder.WriteString(_m.KeyHint)
	builder.WriteString(", ")
	if v := _m.QuotaScopeID; v != nil {
		builder.WriteString("quota_scope_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("secret_payload=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("quota_status=")
	builder.WriteString(_m.QuotaStatus)
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteByte(')')
	return builder.String()
}

// NamedChannelRefs returns the ChannelRefs named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *UpstreamCredential) NamedChannelRefs(name string) ([]*ChannelCredentialRef, error) {
	if _m.Edges.namedChannelRefs == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedChannelRefs[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *UpstreamCredential) appendNamedChannelRefs(name string, edges ...*ChannelCredentialRef) {
	if _m.Edges.namedChannelRefs == nil {
		_m.Edges.namedChannelRefs = make(map[string][]*ChannelCredentialRef)
	}
	if len(edges) == 0 {
		_m.Edges.namedChannelRefs[name] = []*ChannelCredentialRef{}
	} else {
		_m.Edges.namedChannelRefs[name] = append(_m.Edges.namedChannelRefs[name], edges...)
	}
}

// NamedExecutions returns the Executions named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *UpstreamCredential) NamedExecutions(name string) ([]*RequestExecution, error) {
	if _m.Edges.namedExecutions == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedExecutions[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *UpstreamCredential) appendNamedExecutions(name string, edges ...*RequestExecution) {
	if _m.Edges.namedExecutions == nil {
		_m.Edges.namedExecutions = make(map[string][]*RequestExecution)
	}
	if len(edges) == 0 {
		_m.Edges.namedExecutions[name] = []*RequestExecution{}
	} else {
		_m.Edges.namedExecutions[name] = append(_m.Edges.namedExecutions[name], edges...)
	}
}

// NamedUsageLogs returns the UsageLogs named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *UpstreamCredential) NamedUsageLogs(name string) ([]*UsageLog, error) {
	if _m.Edges.namedUsageLogs == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUsageLogs[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *UpstreamCredential) appendNamedUsageLogs(name string, edges ...*UsageLog) {
	if _m.Edges.namedUsageLogs == nil {
		_m.Edges.namedUsageLogs = make(map[string][]*UsageLog)
	}
	if len(edges) == 0 {
		_m.Edges.namedUsageLogs[name] = []*UsageLog{}
	} else {
		_m.Edges.namedUsageLogs[name] = append(_m.Edges.namedUsageLogs[name], edges...)
	}
}

// NamedProviderQuotaStatuses returns the ProviderQuotaStatuses named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *UpstreamCredential) NamedProviderQuotaStatuses(name string) ([]*ProviderQuotaStatus, error) {
	if _m.Edges.namedProviderQuotaStatuses == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedProviderQuotaStatuses[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *UpstreamCredential) appendNamedProviderQuotaStatuses(name string, edges ...*ProviderQuotaStatus) {
	if _m.Edges.namedProviderQuotaStatuses == nil {
		_m.Edges.namedProviderQuotaStatuses = make(map[string][]*ProviderQuotaStatus)
	}
	if len(edges) == 0 {
		_m.Edges.namedProviderQuotaStatuses[name] = []*ProviderQuotaStatus{}
	} else {
		_m.Edges.namedProviderQuotaStatuses[name] = append(_m.Edges.namedProviderQuotaStatuses[name], edges...)
	}
}

// UpstreamCredentials is a parsable slice of UpstreamCredential.
type UpstreamCredentials []*UpstreamCredential
