// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channelcredentialref"
	"github.com/looplj/axonhub/internal/ent/providerquotastatus"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/ent/upstreamcredential"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/objects"
)

// UpstreamCredentialCreate is the builder for creating a UpstreamCredential entity.
type UpstreamCredentialCreate struct {
	config
	mutation *UpstreamCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamCredentialCreate) SetCreatedAt(v time.Time) *UpstreamCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableCreatedAt(v *time.Time) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamCredentialCreate) SetUpdatedAt(v time.Time) *UpstreamCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamCredentialCreate) SetDeletedAt(v int) *UpstreamCredentialCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableDeletedAt(v *int) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamCredentialCreate) SetName(v string) *UpstreamCredentialCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableName(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetProviderType sets the "provider_type" field.
func (_c *UpstreamCredentialCreate) SetProviderType(v string) *UpstreamCredentialCreate {
	_c.mutation.SetProviderType(v)
	return _c
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableProviderType(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetProviderType(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamCredentialCreate) SetBaseURL(v string) *UpstreamCredentialCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableBaseURL(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetBaseURL(*v)
	}
	return _c
}

// SetAuthKind sets the "auth_kind" field.
func (_c *UpstreamCredentialCreate) SetAuthKind(v upstreamcredential.AuthKind) *UpstreamCredentialCreate {
	_c.mutation.SetAuthKind(v)
	return _c
}

// SetNillableAuthKind sets the "auth_kind" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableAuthKind(v *upstreamcredential.AuthKind) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetAuthKind(*v)
	}
	return _c
}

// SetSecretKind sets the "secret_kind" field.
func (_c *UpstreamCredentialCreate) SetSecretKind(v upstreamcredential.SecretKind) *UpstreamCredentialCreate {
	_c.mutation.SetSecretKind(v)
	return _c
}

// SetNillableSecretKind sets the "secret_kind" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableSecretKind(v *upstreamcredential.SecretKind) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetSecretKind(*v)
	}
	return _c
}

// SetIssuerScope sets the "issuer_scope" field.
func (_c *UpstreamCredentialCreate) SetIssuerScope(v string) *UpstreamCredentialCreate {
	_c.mutation.SetIssuerScope(v)
	return _c
}

// SetNillableIssuerScope sets the "issuer_scope" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableIssuerScope(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetIssuerScope(*v)
	}
	return _c
}

// SetKeyHint sets the "key_hint" field.
func (_c *UpstreamCredentialCreate) SetKeyHint(v string) *UpstreamCredentialCreate {
	_c.mutation.SetKeyHint(v)
	return _c
}

// SetNillableKeyHint sets the "key_hint" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableKeyHint(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetKeyHint(*v)
	}
	return _c
}

// SetQuotaScopeID sets the "quota_scope_id" field.
func (_c *UpstreamCredentialCreate) SetQuotaScopeID(v int) *UpstreamCredentialCreate {
	_c.mutation.SetQuotaScopeID(v)
	return _c
}

// SetNillableQuotaScopeID sets the "quota_scope_id" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableQuotaScopeID(v *int) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetQuotaScopeID(*v)
	}
	return _c
}

// SetSecretPayload sets the "secret_payload" field.
func (_c *UpstreamCredentialCreate) SetSecretPayload(v objects.UpstreamCredentialSecret) *UpstreamCredentialCreate {
	_c.mutation.SetSecretPayload(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *UpstreamCredentialCreate) SetFingerprint(v string) *UpstreamCredentialCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamCredentialCreate) SetStatus(v upstreamcredential.Status) *UpstreamCredentialCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableStatus(v *upstreamcredential.Status) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *UpstreamCredentialCreate) SetWeight(v int) *UpstreamCredentialCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableWeight(v *int) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetQuotaStatus sets the "quota_status" field.
func (_c *UpstreamCredentialCreate) SetQuotaStatus(v string) *UpstreamCredentialCreate {
	_c.mutation.SetQuotaStatus(v)
	return _c
}

// SetNillableQuotaStatus sets the "quota_status" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableQuotaStatus(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetQuotaStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *UpstreamCredentialCreate) SetLastError(v string) *UpstreamCredentialCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableLastError(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *UpstreamCredentialCreate) SetRemark(v string) *UpstreamCredentialCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *UpstreamCredentialCreate) SetNillableRemark(v *string) *UpstreamCredentialCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// AddChannelRefIDs adds the "channel_refs" edge to the ChannelCredentialRef entity by IDs.
func (_c *UpstreamCredentialCreate) AddChannelRefIDs(ids ...int) *UpstreamCredentialCreate {
	_c.mutation.AddChannelRefIDs(ids...)
	return _c
}

// AddChannelRefs adds the "channel_refs" edges to the ChannelCredentialRef entity.
func (_c *UpstreamCredentialCreate) AddChannelRefs(v ...*ChannelCredentialRef) *UpstreamCredentialCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChannelRefIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the RequestExecution entity by IDs.
func (_c *UpstreamCredentialCreate) AddExecutionIDs(ids ...int) *UpstreamCredentialCreate {
	_c.mutation.AddExecutionIDs(ids...)
	return _c
}

// AddExecutions adds the "executions" edges to the RequestExecution entity.
func (_c *UpstreamCredentialCreate) AddExecutions(v ...*RequestExecution) *UpstreamCredentialCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExecutionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *UpstreamCredentialCreate) AddUsageLogIDs(ids ...int) *UpstreamCredentialCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *UpstreamCredentialCreate) AddUsageLogs(v ...*UsageLog) *UpstreamCredentialCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// AddProviderQuotaStatusIDs adds the "provider_quota_statuses" edge to the ProviderQuotaStatus entity by IDs.
func (_c *UpstreamCredentialCreate) AddProviderQuotaStatusIDs(ids ...int) *UpstreamCredentialCreate {
	_c.mutation.AddProviderQuotaStatusIDs(ids...)
	return _c
}

// AddProviderQuotaStatuses adds the "provider_quota_statuses" edges to the ProviderQuotaStatus entity.
func (_c *UpstreamCredentialCreate) AddProviderQuotaStatuses(v ...*ProviderQuotaStatus) *UpstreamCredentialCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProviderQuotaStatusIDs(ids...)
}

// Mutation returns the UpstreamCredentialMutation object of the builder.
func (_c *UpstreamCredentialCreate) Mutation() *UpstreamCredentialMutation {
	return _c.mutation
}

// Save creates the UpstreamCredential in the database.
func (_c *UpstreamCredentialCreate) Save(ctx context.Context) (*UpstreamCredential, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamCredentialCreate) SaveX(ctx context.Context) *UpstreamCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamCredentialCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstreamcredential.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamcredential.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstreamcredential.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamcredential.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamcredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := upstreamcredential.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := upstreamcredential.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.ProviderType(); !ok {
		v := upstreamcredential.DefaultProviderType
		_c.mutation.SetProviderType(v)
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		v := upstreamcredential.DefaultBaseURL
		_c.mutation.SetBaseURL(v)
	}
	if _, ok := _c.mutation.AuthKind(); !ok {
		v := upstreamcredential.DefaultAuthKind
		_c.mutation.SetAuthKind(v)
	}
	if _, ok := _c.mutation.SecretKind(); !ok {
		v := upstreamcredential.DefaultSecretKind
		_c.mutation.SetSecretKind(v)
	}
	if _, ok := _c.mutation.IssuerScope(); !ok {
		v := upstreamcredential.DefaultIssuerScope
		_c.mutation.SetIssuerScope(v)
	}
	if _, ok := _c.mutation.KeyHint(); !ok {
		v := upstreamcredential.DefaultKeyHint
		_c.mutation.SetKeyHint(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstreamcredential.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := upstreamcredential.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.QuotaStatus(); !ok {
		v := upstreamcredential.DefaultQuotaStatus
		_c.mutation.SetQuotaStatus(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := upstreamcredential.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := upstreamcredential.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamCredentialCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "UpstreamCredential.deleted_at"`)}
	}
	if _, ok := _c.mutation.ProviderType(); !ok {
		return &ValidationError{Name: "provider_type", err: errors.New(`ent: missing required field "UpstreamCredential.provider_type"`)}
	}
	if _, ok := _c.mutation.AuthKind(); !ok {
		return &ValidationError{Name: "auth_kind", err: errors.New(`ent: missing required field "UpstreamCredential.auth_kind"`)}
	}
	if v, ok := _c.mutation.AuthKind(); ok {
		if err := upstreamcredential.AuthKindValidator(v); err != nil {
			return &ValidationError{Name: "auth_kind", err: fmt.Errorf(`ent: validator failed for field "UpstreamCredential.auth_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretKind(); !ok {
		return &ValidationError{Name: "secret_kind", err: errors.New(`ent: missing required field "UpstreamCredential.secret_kind"`)}
	}
	if v, ok := _c.mutation.SecretKind(); ok {
		if err := upstreamcredential.SecretKindValidator(v); err != nil {
			return &ValidationError{Name: "secret_kind", err: fmt.Errorf(`ent: validator failed for field "UpstreamCredential.secret_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretPayload(); !ok {
		return &ValidationError{Name: "secret_payload", err: errors.New(`ent: missing required field "UpstreamCredential.secret_payload"`)}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "UpstreamCredential.fingerprint"`)}
	}
	if v, ok := _c.mutation.Fingerprint(); ok {
		if err := upstreamcredential.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "UpstreamCredential.fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamCredential.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreamcredential.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamCredential.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "UpstreamCredential.weight"`)}
	}
	return nil
}

func (_c *UpstreamCredentialCreate) sqlSave(ctx context.Context) (*UpstreamCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamCredentialCreate) createSpec() (*UpstreamCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamcredential.Table, sqlgraph.NewFieldSpec(upstreamcredential.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamcredential.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamcredential.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ProviderType(); ok {
		_spec.SetField(upstreamcredential.FieldProviderType, field.TypeString, value)
		_node.ProviderType = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstreamcredential.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.AuthKind(); ok {
		_spec.SetField(upstreamcredential.FieldAuthKind, field.TypeEnum, value)
		_node.AuthKind = value
	}
	if value, ok := _c.mutation.SecretKind(); ok {
		_spec.SetField(upstreamcredential.FieldSecretKind, field.TypeEnum, value)
		_node.SecretKind = value
	}
	if value, ok := _c.mutation.IssuerScope(); ok {
		_spec.SetField(upstreamcredential.FieldIssuerScope, field.TypeString, value)
		_node.IssuerScope = value
	}
	if value, ok := _c.mutation.KeyHint(); ok {
		_spec.SetField(upstreamcredential.FieldKeyHint, field.TypeString, value)
		_node.KeyHint = value
	}
	if value, ok := _c.mutation.QuotaScopeID(); ok {
		_spec.SetField(upstreamcredential.FieldQuotaScopeID, field.TypeInt, value)
		_node.QuotaScopeID = &value
	}
	if value, ok := _c.mutation.SecretPayload(); ok {
		_spec.SetField(upstreamcredential.FieldSecretPayload, field.TypeJSON, value)
		_node.SecretPayload = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(upstreamcredential.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreamcredential.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(upstreamcredential.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.QuotaStatus(); ok {
		_spec.SetField(upstreamcredential.FieldQuotaStatus, field.TypeString, value)
		_node.QuotaStatus = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(upstreamcredential.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(upstreamcredential.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if nodes := _c.mutation.ChannelRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamcredential.ChannelRefsTable,
			Columns: []string{upstreamcredential.ChannelRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelcredentialref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamcredential.ExecutionsTable,
			Columns: []string{upstreamcredential.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamcredential.UsageLogsTable,
			Columns: []string{upstreamcredential.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProviderQuotaStatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamcredential.ProviderQuotaStatusesTable,
			Columns: []string{upstreamcredential.ProviderQuotaStatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerquotastatus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamCredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCredentialCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamCredentialUpsertOne {
	_c.conflict = opts
	return &UpstreamCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCredentialCreate) OnConflictColumns(columns ...string) *UpstreamCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamCredentialUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamCredentialUpsertOne is the builder for "upsert"-ing
	//  one UpstreamCredential node.
	UpstreamCredentialUpsertOne struct {
		create *UpstreamCredentialCreate
	}

	// UpstreamCredentialUpsert is the "OnConflict" setter.
	UpstreamCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamCredentialUpsert) SetUpdatedAt(v time.Time) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateUpdatedAt() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamCredentialUpsert) SetDeletedAt(v int) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateDeletedAt() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *UpstreamCredentialUpsert) AddDeletedAt(v int) *UpstreamCredentialUpsert {
	u.Add(upstreamcredential.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamCredentialUpsert) SetName(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateName() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *UpstreamCredentialUpsert) ClearName() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldName)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamCredentialUpsert) SetBaseURL(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateBaseURL() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldBaseURL)
	return u
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *UpstreamCredentialUpsert) ClearBaseURL() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldBaseURL)
	return u
}

// SetSecretKind sets the "secret_kind" field.
func (u *UpstreamCredentialUpsert) SetSecretKind(v upstreamcredential.SecretKind) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldSecretKind, v)
	return u
}

// UpdateSecretKind sets the "secret_kind" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateSecretKind() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldSecretKind)
	return u
}

// SetIssuerScope sets the "issuer_scope" field.
func (u *UpstreamCredentialUpsert) SetIssuerScope(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldIssuerScope, v)
	return u
}

// UpdateIssuerScope sets the "issuer_scope" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateIssuerScope() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldIssuerScope)
	return u
}

// ClearIssuerScope clears the value of the "issuer_scope" field.
func (u *UpstreamCredentialUpsert) ClearIssuerScope() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldIssuerScope)
	return u
}

// SetKeyHint sets the "key_hint" field.
func (u *UpstreamCredentialUpsert) SetKeyHint(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldKeyHint, v)
	return u
}

// UpdateKeyHint sets the "key_hint" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateKeyHint() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldKeyHint)
	return u
}

// ClearKeyHint clears the value of the "key_hint" field.
func (u *UpstreamCredentialUpsert) ClearKeyHint() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldKeyHint)
	return u
}

// SetQuotaScopeID sets the "quota_scope_id" field.
func (u *UpstreamCredentialUpsert) SetQuotaScopeID(v int) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldQuotaScopeID, v)
	return u
}

// UpdateQuotaScopeID sets the "quota_scope_id" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateQuotaScopeID() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldQuotaScopeID)
	return u
}

// AddQuotaScopeID adds v to the "quota_scope_id" field.
func (u *UpstreamCredentialUpsert) AddQuotaScopeID(v int) *UpstreamCredentialUpsert {
	u.Add(upstreamcredential.FieldQuotaScopeID, v)
	return u
}

// ClearQuotaScopeID clears the value of the "quota_scope_id" field.
func (u *UpstreamCredentialUpsert) ClearQuotaScopeID() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldQuotaScopeID)
	return u
}

// SetSecretPayload sets the "secret_payload" field.
func (u *UpstreamCredentialUpsert) SetSecretPayload(v objects.UpstreamCredentialSecret) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldSecretPayload, v)
	return u
}

// UpdateSecretPayload sets the "secret_payload" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateSecretPayload() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldSecretPayload)
	return u
}

// SetFingerprint sets the "fingerprint" field.
func (u *UpstreamCredentialUpsert) SetFingerprint(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldFingerprint, v)
	return u
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateFingerprint() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldFingerprint)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamCredentialUpsert) SetStatus(v upstreamcredential.Status) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateStatus() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldStatus)
	return u
}

// SetWeight sets the "weight" field.
func (u *UpstreamCredentialUpsert) SetWeight(v int) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateWeight() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *UpstreamCredentialUpsert) AddWeight(v int) *UpstreamCredentialUpsert {
	u.Add(upstreamcredential.FieldWeight, v)
	return u
}

// SetQuotaStatus sets the "quota_status" field.
func (u *UpstreamCredentialUpsert) SetQuotaStatus(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldQuotaStatus, v)
	return u
}

// UpdateQuotaStatus sets the "quota_status" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateQuotaStatus() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldQuotaStatus)
	return u
}

// ClearQuotaStatus clears the value of the "quota_status" field.
func (u *UpstreamCredentialUpsert) ClearQuotaStatus() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldQuotaStatus)
	return u
}

// SetLastError sets the "last_error" field.
func (u *UpstreamCredentialUpsert) SetLastError(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateLastError() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamCredentialUpsert) ClearLastError() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldLastError)
	return u
}

// SetRemark sets the "remark" field.
func (u *UpstreamCredentialUpsert) SetRemark(v string) *UpstreamCredentialUpsert {
	u.Set(upstreamcredential.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *UpstreamCredentialUpsert) UpdateRemark() *UpstreamCredentialUpsert {
	u.SetExcluded(upstreamcredential.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *UpstreamCredentialUpsert) ClearRemark() *UpstreamCredentialUpsert {
	u.SetNull(upstreamcredential.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamCredentialUpsertOne) UpdateNewValues() *UpstreamCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamcredential.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ProviderType(); exists {
			s.SetIgnore(upstreamcredential.FieldProviderType)
		}
		if _, exists := u.create.mutation.AuthKind(); exists {
			s.SetIgnore(upstreamcredential.FieldAuthKind)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamCredentialUpsertOne) Ignore() *UpstreamCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamCredentialUpsertOne) DoNothing() *UpstreamCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCredentialCreate.OnConflict
// documentation for more info.
func (u *UpstreamCredentialUpsertOne) Update(set func(*UpstreamCredentialUpsert)) *UpstreamCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamCredentialUpsertOne) SetUpdatedAt(v time.Time) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateUpdatedAt() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamCredentialUpsertOne) SetDeletedAt(v int) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *UpstreamCredentialUpsertOne) AddDeletedAt(v int) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateDeletedAt() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamCredentialUpsertOne) SetName(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateName() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UpstreamCredentialUpsertOne) ClearName() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamCredentialUpsertOne) SetBaseURL(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateBaseURL() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateBaseURL()
	})
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *UpstreamCredentialUpsertOne) ClearBaseURL() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearBaseURL()
	})
}

// SetSecretKind sets the "secret_kind" field.
func (u *UpstreamCredentialUpsertOne) SetSecretKind(v upstreamcredential.SecretKind) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetSecretKind(v)
	})
}

// UpdateSecretKind sets the "secret_kind" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateSecretKind() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateSecretKind()
	})
}

// SetIssuerScope sets the "issuer_scope" field.
func (u *UpstreamCredentialUpsertOne) SetIssuerScope(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetIssuerScope(v)
	})
}

// UpdateIssuerScope sets the "issuer_scope" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateIssuerScope() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateIssuerScope()
	})
}

// ClearIssuerScope clears the value of the "issuer_scope" field.
func (u *UpstreamCredentialUpsertOne) ClearIssuerScope() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearIssuerScope()
	})
}

// SetKeyHint sets the "key_hint" field.
func (u *UpstreamCredentialUpsertOne) SetKeyHint(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetKeyHint(v)
	})
}

// UpdateKeyHint sets the "key_hint" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateKeyHint() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateKeyHint()
	})
}

// ClearKeyHint clears the value of the "key_hint" field.
func (u *UpstreamCredentialUpsertOne) ClearKeyHint() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearKeyHint()
	})
}

// SetQuotaScopeID sets the "quota_scope_id" field.
func (u *UpstreamCredentialUpsertOne) SetQuotaScopeID(v int) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetQuotaScopeID(v)
	})
}

// AddQuotaScopeID adds v to the "quota_scope_id" field.
func (u *UpstreamCredentialUpsertOne) AddQuotaScopeID(v int) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.AddQuotaScopeID(v)
	})
}

// UpdateQuotaScopeID sets the "quota_scope_id" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateQuotaScopeID() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateQuotaScopeID()
	})
}

// ClearQuotaScopeID clears the value of the "quota_scope_id" field.
func (u *UpstreamCredentialUpsertOne) ClearQuotaScopeID() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearQuotaScopeID()
	})
}

// SetSecretPayload sets the "secret_payload" field.
func (u *UpstreamCredentialUpsertOne) SetSecretPayload(v objects.UpstreamCredentialSecret) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetSecretPayload(v)
	})
}

// UpdateSecretPayload sets the "secret_payload" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateSecretPayload() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateSecretPayload()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *UpstreamCredentialUpsertOne) SetFingerprint(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateFingerprint() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateFingerprint()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamCredentialUpsertOne) SetStatus(v upstreamcredential.Status) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateStatus() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateStatus()
	})
}

// SetWeight sets the "weight" field.
func (u *UpstreamCredentialUpsertOne) SetWeight(v int) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *UpstreamCredentialUpsertOne) AddWeight(v int) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateWeight() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateWeight()
	})
}

// SetQuotaStatus sets the "quota_status" field.
func (u *UpstreamCredentialUpsertOne) SetQuotaStatus(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetQuotaStatus(v)
	})
}

// UpdateQuotaStatus sets the "quota_status" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateQuotaStatus() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateQuotaStatus()
	})
}

// ClearQuotaStatus clears the value of the "quota_status" field.
func (u *UpstreamCredentialUpsertOne) ClearQuotaStatus() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearQuotaStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamCredentialUpsertOne) SetLastError(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateLastError() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamCredentialUpsertOne) ClearLastError() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearLastError()
	})
}

// SetRemark sets the "remark" field.
func (u *UpstreamCredentialUpsertOne) SetRemark(v string) *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertOne) UpdateRemark() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *UpstreamCredentialUpsertOne) ClearRemark() *UpstreamCredentialUpsertOne {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *UpstreamCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamCredentialUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamCredentialUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamCredentialCreateBulk is the builder for creating many UpstreamCredential entities in bulk.
type UpstreamCredentialCreateBulk struct {
	config
	err      error
	builders []*UpstreamCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamCredential entities in the database.
func (_c *UpstreamCredentialCreateBulk) Save(ctx context.Context) ([]*UpstreamCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamCredentialCreateBulk) SaveX(ctx context.Context) []*UpstreamCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamCredentialUpsertBulk {
	_c.conflict = opts
	return &UpstreamCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCredentialCreateBulk) OnConflictColumns(columns ...string) *UpstreamCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamCredentialUpsertBulk{
		create: _c,
	}
}

// UpstreamCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamCredential nodes.
type UpstreamCredentialUpsertBulk struct {
	create *UpstreamCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamCredentialUpsertBulk) UpdateNewValues() *UpstreamCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamcredential.FieldCreatedAt)
			}
			if _, exists := b.mutation.ProviderType(); exists {
				s.SetIgnore(upstreamcredential.FieldProviderType)
			}
			if _, exists := b.mutation.AuthKind(); exists {
				s.SetIgnore(upstreamcredential.FieldAuthKind)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamCredentialUpsertBulk) Ignore() *UpstreamCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamCredentialUpsertBulk) DoNothing() *UpstreamCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamCredentialUpsertBulk) Update(set func(*UpstreamCredentialUpsert)) *UpstreamCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamCredentialUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateUpdatedAt() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamCredentialUpsertBulk) SetDeletedAt(v int) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *UpstreamCredentialUpsertBulk) AddDeletedAt(v int) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateDeletedAt() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamCredentialUpsertBulk) SetName(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateName() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UpstreamCredentialUpsertBulk) ClearName() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamCredentialUpsertBulk) SetBaseURL(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateBaseURL() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateBaseURL()
	})
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *UpstreamCredentialUpsertBulk) ClearBaseURL() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearBaseURL()
	})
}

// SetSecretKind sets the "secret_kind" field.
func (u *UpstreamCredentialUpsertBulk) SetSecretKind(v upstreamcredential.SecretKind) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetSecretKind(v)
	})
}

// UpdateSecretKind sets the "secret_kind" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateSecretKind() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateSecretKind()
	})
}

// SetIssuerScope sets the "issuer_scope" field.
func (u *UpstreamCredentialUpsertBulk) SetIssuerScope(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetIssuerScope(v)
	})
}

// UpdateIssuerScope sets the "issuer_scope" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateIssuerScope() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateIssuerScope()
	})
}

// ClearIssuerScope clears the value of the "issuer_scope" field.
func (u *UpstreamCredentialUpsertBulk) ClearIssuerScope() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearIssuerScope()
	})
}

// SetKeyHint sets the "key_hint" field.
func (u *UpstreamCredentialUpsertBulk) SetKeyHint(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetKeyHint(v)
	})
}

// UpdateKeyHint sets the "key_hint" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateKeyHint() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateKeyHint()
	})
}

// ClearKeyHint clears the value of the "key_hint" field.
func (u *UpstreamCredentialUpsertBulk) ClearKeyHint() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearKeyHint()
	})
}

// SetQuotaScopeID sets the "quota_scope_id" field.
func (u *UpstreamCredentialUpsertBulk) SetQuotaScopeID(v int) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetQuotaScopeID(v)
	})
}

// AddQuotaScopeID adds v to the "quota_scope_id" field.
func (u *UpstreamCredentialUpsertBulk) AddQuotaScopeID(v int) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.AddQuotaScopeID(v)
	})
}

// UpdateQuotaScopeID sets the "quota_scope_id" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateQuotaScopeID() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateQuotaScopeID()
	})
}

// ClearQuotaScopeID clears the value of the "quota_scope_id" field.
func (u *UpstreamCredentialUpsertBulk) ClearQuotaScopeID() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearQuotaScopeID()
	})
}

// SetSecretPayload sets the "secret_payload" field.
func (u *UpstreamCredentialUpsertBulk) SetSecretPayload(v objects.UpstreamCredentialSecret) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetSecretPayload(v)
	})
}

// UpdateSecretPayload sets the "secret_payload" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateSecretPayload() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateSecretPayload()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *UpstreamCredentialUpsertBulk) SetFingerprint(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateFingerprint() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateFingerprint()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamCredentialUpsertBulk) SetStatus(v upstreamcredential.Status) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateStatus() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateStatus()
	})
}

// SetWeight sets the "weight" field.
func (u *UpstreamCredentialUpsertBulk) SetWeight(v int) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *UpstreamCredentialUpsertBulk) AddWeight(v int) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateWeight() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateWeight()
	})
}

// SetQuotaStatus sets the "quota_status" field.
func (u *UpstreamCredentialUpsertBulk) SetQuotaStatus(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetQuotaStatus(v)
	})
}

// UpdateQuotaStatus sets the "quota_status" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateQuotaStatus() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateQuotaStatus()
	})
}

// ClearQuotaStatus clears the value of the "quota_status" field.
func (u *UpstreamCredentialUpsertBulk) ClearQuotaStatus() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearQuotaStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamCredentialUpsertBulk) SetLastError(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateLastError() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamCredentialUpsertBulk) ClearLastError() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearLastError()
	})
}

// SetRemark sets the "remark" field.
func (u *UpstreamCredentialUpsertBulk) SetRemark(v string) *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *UpstreamCredentialUpsertBulk) UpdateRemark() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *UpstreamCredentialUpsertBulk) ClearRemark() *UpstreamCredentialUpsertBulk {
	return u.Update(func(s *UpstreamCredentialUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *UpstreamCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
