// Code generated by ent, DO NOT EDIT.

package credentialquotascope

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the credentialquotascope type in the database.
	Label = "credential_quota_scope"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldLimitAmount holds the string denoting the limit_amount field in the database.
	FieldLimitAmount = "limit_amount"
	// FieldUsedAmount holds the string denoting the used_amount field in the database.
	FieldUsedAmount = "used_amount"
	// FieldWarningThresholdPercent holds the string denoting the warning_threshold_percent field in the database.
	FieldWarningThresholdPercent = "warning_threshold_percent"
	// FieldResetPolicy holds the string denoting the reset_policy field in the database.
	FieldResetPolicy = "reset_policy"
	// FieldResetAt holds the string denoting the reset_at field in the database.
	FieldResetAt = "reset_at"
	// FieldWindowStartedAt holds the string denoting the window_started_at field in the database.
	FieldWindowStartedAt = "window_started_at"
	// FieldOverLimitAction holds the string denoting the over_limit_action field in the database.
	FieldOverLimitAction = "over_limit_action"
	// FieldPauseUntil holds the string denoting the pause_until field in the database.
	FieldPauseUntil = "pause_until"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeCredentials holds the string denoting the credentials edge name in mutations.
	EdgeCredentials = "credentials"
	// EdgeProviderQuotaStatuses holds the string denoting the provider_quota_statuses edge name in mutations.
	EdgeProviderQuotaStatuses = "provider_quota_statuses"
	// EdgeExecutions holds the string denoting the executions edge name in mutations.
	EdgeExecutions = "executions"
	// EdgeUsageLogs holds the string denoting the usage_logs edge name in mutations.
	EdgeUsageLogs = "usage_logs"
	// Table holds the table name of the credentialquotascope in the database.
	Table = "credential_quota_scopes"
	// CredentialsTable is the table that holds the credentials relation/edge.
	CredentialsTable = "upstream_credentials"
	// CredentialsInverseTable is the table name for the UpstreamCredential entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamcredential" package.
	CredentialsInverseTable = "upstream_credentials"
	// CredentialsColumn is the table column denoting the credentials relation/edge.
	CredentialsColumn = "quota_scope_id"
	// ProviderQuotaStatusesTable is the table that holds the provider_quota_statuses relation/edge.
	ProviderQuotaStatusesTable = "provider_quota_status"
	// ProviderQuotaStatusesInverseTable is the table name for the ProviderQuotaStatus entity.
	// It exists in this package in order to avoid circular dependency with the "providerquotastatus" package.
	ProviderQuotaStatusesInverseTable = "provider_quota_status"
	// ProviderQuotaStatusesColumn is the table column denoting the provider_quota_statuses relation/edge.
	ProviderQuotaStatusesColumn = "quota_scope_id"
	// ExecutionsTable is the table that holds the executions relation/edge.
	ExecutionsTable = "request_executions"
	// ExecutionsInverseTable is the table name for the RequestExecution entity.
	// It exists in this package in order to avoid circular dependency with the "requestexecution" package.
	ExecutionsInverseTable = "request_executions"
	// ExecutionsColumn is the table column denoting the executions relation/edge.
	ExecutionsColumn = "quota_scope_id"
	// UsageLogsTable is the table that holds the usage_logs relation/edge.
	UsageLogsTable = "usage_logs"
	// UsageLogsInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogsInverseTable = "usage_logs"
	// UsageLogsColumn is the table column denoting the usage_logs relation/edge.
	UsageLogsColumn = "quota_scope_id"
)

// Columns holds all SQL columns for credentialquotascope fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldStatus,
	FieldUnit,
	FieldLimitAmount,
	FieldUsedAmount,
	FieldWarningThresholdPercent,
	FieldResetPolicy,
	FieldResetAt,
	FieldWindowStartedAt,
	FieldOverLimitAction,
	FieldPauseUntil,
	FieldSource,
	FieldLastError,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultLimitAmount holds the default value on creation for the "limit_amount" field.
	DefaultLimitAmount string
	// DefaultUsedAmount holds the default value on creation for the "used_amount" field.
	DefaultUsedAmount string
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnknown is the default value of the Status enum.
const DefaultStatus = StatusUnknown

// Status values.
const (
	StatusAvailable Status = "available"
	StatusWarning   Status = "warning"
	StatusExhausted Status = "exhausted"
	StatusPaused    Status = "paused"
	StatusDisabled  Status = "disabled"
	StatusUnknown   Status = "unknown"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusWarning, StatusExhausted, StatusPaused, StatusDisabled, StatusUnknown:
		return nil
	default:
		return fmt.Errorf("credentialquotascope: invalid enum value for status field: %q", s)
	}
}

// Unit defines the type for the "unit" enum field.
type Unit string

// UnitUnknown is the default value of the Unit enum.
const DefaultUnit = UnitUnknown

// Unit values.
const (
	UnitUsd     Unit = "usd"
	UnitToken   Unit = "token"
	UnitRequest Unit = "request"
	UnitCredit  Unit = "credit"
	UnitCustom  Unit = "custom"
	UnitUnknown Unit = "unknown"
)

func (u Unit) String() string {
	return string(u)
}

// UnitValidator is a validator for the "unit" field enum values. It is called by the builders before save.
func UnitValidator(u Unit) error {
	switch u {
	case UnitUsd, UnitToken, UnitRequest, UnitCredit, UnitCustom, UnitUnknown:
		return nil
	default:
		return fmt.Errorf("credentialquotascope: invalid enum value for unit field: %q", u)
	}
}

// ResetPolicy defines the type for the "reset_policy" enum field.
type ResetPolicy string

// ResetPolicyNone is the default value of the ResetPolicy enum.
const DefaultResetPolicy = ResetPolicyNone

// ResetPolicy values.
const (
	ResetPolicyNone    ResetPolicy = "none"
	ResetPolicyManual  ResetPolicy = "manual"
	ResetPolicyDaily   ResetPolicy = "daily"
	ResetPolicyMonthly ResetPolicy = "monthly"
	ResetPolicyCustom  ResetPolicy = "custom"
)

func (rp ResetPolicy) String() string {
	return string(rp)
}

// ResetPolicyValidator is a validator for the "reset_policy" field enum values. It is called by the builders before save.
func ResetPolicyValidator(rp ResetPolicy) error {
	switch rp {
	case ResetPolicyNone, ResetPolicyManual, ResetPolicyDaily, ResetPolicyMonthly, ResetPolicyCustom:
		return nil
	default:
		return fmt.Errorf("credentialquotascope: invalid enum value for reset_policy field: %q", rp)
	}
}

// OverLimitAction defines the type for the "over_limit_action" enum field.
type OverLimitAction string

// OverLimitActionWarn is the default value of the OverLimitAction enum.
const DefaultOverLimitAction = OverLimitActionWarn

// OverLimitAction values.
const (
	OverLimitActionWarn    OverLimitAction = "warn"
	OverLimitActionPause   OverLimitAction = "pause"
	OverLimitActionDisable OverLimitAction = "disable"
)

func (ola OverLimitAction) String() string {
	return string(ola)
}

// OverLimitActionValidator is a validator for the "over_limit_action" field enum values. It is called by the builders before save.
func OverLimitActionValidator(ola OverLimitAction) error {
	switch ola {
	case OverLimitActionWarn, OverLimitActionPause, OverLimitActionDisable:
		return nil
	default:
		return fmt.Errorf("credentialquotascope: invalid enum value for over_limit_action field: %q", ola)
	}
}

// Source defines the type for the "source" enum field.
type Source string

// SourceLocalBudget is the default value of the Source enum.
const DefaultSource = SourceLocalBudget

// Source values.
const (
	SourceLocalBudget   Source = "local_budget"
	SourceProviderAPI   Source = "provider_api"
	SourceResponseError Source = "response_error"
	SourceManual        Source = "manual"
	SourceInferred      Source = "inferred"
	SourceUnknown       Source = "unknown"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceLocalBudget, SourceProviderAPI, SourceResponseError, SourceManual, SourceInferred, SourceUnknown:
		return nil
	default:
		return fmt.Errorf("credentialquotascope: invalid enum value for source field: %q", s)
	}
}

// OrderOption defines the ordering options for the CredentialQuotaScope queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUnit orders the results by the unit field.
func ByUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnit, opts...).ToFunc()
}

// ByLimitAmount orders the results by the limit_amount field.
func ByLimitAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLimitAmount, opts...).ToFunc()
}

// ByUsedAmount orders the results by the used_amount field.
func ByUsedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAmount, opts...).ToFunc()
}

// ByWarningThresholdPercent orders the results by the warning_threshold_percent field.
func ByWarningThresholdPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarningThresholdPercent, opts...).ToFunc()
}

// ByResetPolicy orders the results by the reset_policy field.
func ByResetPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetPolicy, opts...).ToFunc()
}

// ByResetAt orders the results by the reset_at field.
func ByResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetAt, opts...).ToFunc()
}

// ByWindowStartedAt orders the results by the window_started_at field.
func ByWindowStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowStartedAt, opts...).ToFunc()
}

// ByOverLimitAction orders the results by the over_limit_action field.
func ByOverLimitAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverLimitAction, opts...).ToFunc()
}

// ByPauseUntil orders the results by the pause_until field.
func ByPauseUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPauseUntil, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByCredentialsCount orders the results by credentials count.
func ByCredentialsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCredentialsStep(), opts...)
	}
}

// ByCredentials orders the results by credentials terms.
func ByCredentials(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCredentialsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProviderQuotaStatusesCount orders the results by provider_quota_statuses count.
func ByProviderQuotaStatusesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProviderQuotaStatusesStep(), opts...)
	}
}

// ByProviderQuotaStatuses orders the results by provider_quota_statuses terms.
func ByProviderQuotaStatuses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderQuotaStatusesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExecutionsCount orders the results by executions count.
func ByExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExecutionsStep(), opts...)
	}
}

// ByExecutions orders the results by executions terms.
func ByExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsageLogsCount orders the results by usage_logs count.
func ByUsageLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageLogsStep(), opts...)
	}
}

// ByUsageLogs orders the results by usage_logs terms.
func ByUsageLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCredentialsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CredentialsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CredentialsTable, CredentialsColumn),
	)
}
func newProviderQuotaStatusesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderQuotaStatusesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProviderQuotaStatusesTable, ProviderQuotaStatusesColumn),
	)
}
func newExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExecutionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExecutionsTable, ExecutionsColumn),
	)
}
func newUsageLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Unit) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Unit) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Unit(str)
	if err := UnitValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Unit", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e ResetPolicy) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *ResetPolicy) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = ResetPolicy(str)
	if err := ResetPolicyValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid ResetPolicy", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e OverLimitAction) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *OverLimitAction) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = OverLimitAction(str)
	if err := OverLimitActionValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid OverLimitAction", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Source) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Source) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Source(str)
	if err := SourceValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Source", str)
	}
	return nil
}
