// Code generated by ent, DO NOT EDIT.

package credentialquotascope

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldName, v))
}

// LimitAmount applies equality check predicate on the "limit_amount" field. It's identical to LimitAmountEQ.
func LimitAmount(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldLimitAmount, v))
}

// UsedAmount applies equality check predicate on the "used_amount" field. It's identical to UsedAmountEQ.
func UsedAmount(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldUsedAmount, v))
}

// WarningThresholdPercent applies equality check predicate on the "warning_threshold_percent" field. It's identical to WarningThresholdPercentEQ.
func WarningThresholdPercent(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldWarningThresholdPercent, v))
}

// ResetAt applies equality check predicate on the "reset_at" field. It's identical to ResetAtEQ.
func ResetAt(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldResetAt, v))
}

// WindowStartedAt applies equality check predicate on the "window_started_at" field. It's identical to WindowStartedAtEQ.
func WindowStartedAt(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldWindowStartedAt, v))
}

// PauseUntil applies equality check predicate on the "pause_until" field. It's identical to PauseUntilEQ.
func PauseUntil(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldPauseUntil, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldLastError, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldStatus, vs...))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v Unit) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v Unit) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...Unit) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...Unit) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldUnit, vs...))
}

// LimitAmountEQ applies the EQ predicate on the "limit_amount" field.
func LimitAmountEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldLimitAmount, v))
}

// LimitAmountNEQ applies the NEQ predicate on the "limit_amount" field.
func LimitAmountNEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldLimitAmount, v))
}

// LimitAmountIn applies the In predicate on the "limit_amount" field.
func LimitAmountIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldLimitAmount, vs...))
}

// LimitAmountNotIn applies the NotIn predicate on the "limit_amount" field.
func LimitAmountNotIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldLimitAmount, vs...))
}

// LimitAmountGT applies the GT predicate on the "limit_amount" field.
func LimitAmountGT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldLimitAmount, v))
}

// LimitAmountGTE applies the GTE predicate on the "limit_amount" field.
func LimitAmountGTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldLimitAmount, v))
}

// LimitAmountLT applies the LT predicate on the "limit_amount" field.
func LimitAmountLT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldLimitAmount, v))
}

// LimitAmountLTE applies the LTE predicate on the "limit_amount" field.
func LimitAmountLTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldLimitAmount, v))
}

// LimitAmountContains applies the Contains predicate on the "limit_amount" field.
func LimitAmountContains(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContains(FieldLimitAmount, v))
}

// LimitAmountHasPrefix applies the HasPrefix predicate on the "limit_amount" field.
func LimitAmountHasPrefix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasPrefix(FieldLimitAmount, v))
}

// LimitAmountHasSuffix applies the HasSuffix predicate on the "limit_amount" field.
func LimitAmountHasSuffix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasSuffix(FieldLimitAmount, v))
}

// LimitAmountIsNil applies the IsNil predicate on the "limit_amount" field.
func LimitAmountIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldLimitAmount))
}

// LimitAmountNotNil applies the NotNil predicate on the "limit_amount" field.
func LimitAmountNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldLimitAmount))
}

// LimitAmountEqualFold applies the EqualFold predicate on the "limit_amount" field.
func LimitAmountEqualFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEqualFold(FieldLimitAmount, v))
}

// LimitAmountContainsFold applies the ContainsFold predicate on the "limit_amount" field.
func LimitAmountContainsFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContainsFold(FieldLimitAmount, v))
}

// UsedAmountEQ applies the EQ predicate on the "used_amount" field.
func UsedAmountEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldUsedAmount, v))
}

// UsedAmountNEQ applies the NEQ predicate on the "used_amount" field.
func UsedAmountNEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldUsedAmount, v))
}

// UsedAmountIn applies the In predicate on the "used_amount" field.
func UsedAmountIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldUsedAmount, vs...))
}

// UsedAmountNotIn applies the NotIn predicate on the "used_amount" field.
func UsedAmountNotIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldUsedAmount, vs...))
}

// UsedAmountGT applies the GT predicate on the "used_amount" field.
func UsedAmountGT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldUsedAmount, v))
}

// UsedAmountGTE applies the GTE predicate on the "used_amount" field.
func UsedAmountGTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldUsedAmount, v))
}

// UsedAmountLT applies the LT predicate on the "used_amount" field.
func UsedAmountLT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldUsedAmount, v))
}

// UsedAmountLTE applies the LTE predicate on the "used_amount" field.
func UsedAmountLTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldUsedAmount, v))
}

// UsedAmountContains applies the Contains predicate on the "used_amount" field.
func UsedAmountContains(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContains(FieldUsedAmount, v))
}

// UsedAmountHasPrefix applies the HasPrefix predicate on the "used_amount" field.
func UsedAmountHasPrefix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasPrefix(FieldUsedAmount, v))
}

// UsedAmountHasSuffix applies the HasSuffix predicate on the "used_amount" field.
func UsedAmountHasSuffix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasSuffix(FieldUsedAmount, v))
}

// UsedAmountIsNil applies the IsNil predicate on the "used_amount" field.
func UsedAmountIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldUsedAmount))
}

// UsedAmountNotNil applies the NotNil predicate on the "used_amount" field.
func UsedAmountNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldUsedAmount))
}

// UsedAmountEqualFold applies the EqualFold predicate on the "used_amount" field.
func UsedAmountEqualFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEqualFold(FieldUsedAmount, v))
}

// UsedAmountContainsFold applies the ContainsFold predicate on the "used_amount" field.
func UsedAmountContainsFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContainsFold(FieldUsedAmount, v))
}

// WarningThresholdPercentEQ applies the EQ predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentEQ(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldWarningThresholdPercent, v))
}

// WarningThresholdPercentNEQ applies the NEQ predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentNEQ(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldWarningThresholdPercent, v))
}

// WarningThresholdPercentIn applies the In predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentIn(vs ...int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldWarningThresholdPercent, vs...))
}

// WarningThresholdPercentNotIn applies the NotIn predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentNotIn(vs ...int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldWarningThresholdPercent, vs...))
}

// WarningThresholdPercentGT applies the GT predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentGT(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldWarningThresholdPercent, v))
}

// WarningThresholdPercentGTE applies the GTE predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentGTE(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldWarningThresholdPercent, v))
}

// WarningThresholdPercentLT applies the LT predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentLT(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldWarningThresholdPercent, v))
}

// WarningThresholdPercentLTE applies the LTE predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentLTE(v int) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldWarningThresholdPercent, v))
}

// WarningThresholdPercentIsNil applies the IsNil predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldWarningThresholdPercent))
}

// WarningThresholdPercentNotNil applies the NotNil predicate on the "warning_threshold_percent" field.
func WarningThresholdPercentNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldWarningThresholdPercent))
}

// ResetPolicyEQ applies the EQ predicate on the "reset_policy" field.
func ResetPolicyEQ(v ResetPolicy) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldResetPolicy, v))
}

// ResetPolicyNEQ applies the NEQ predicate on the "reset_policy" field.
func ResetPolicyNEQ(v ResetPolicy) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldResetPolicy, v))
}

// ResetPolicyIn applies the In predicate on the "reset_policy" field.
func ResetPolicyIn(vs ...ResetPolicy) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldResetPolicy, vs...))
}

// ResetPolicyNotIn applies the NotIn predicate on the "reset_policy" field.
func ResetPolicyNotIn(vs ...ResetPolicy) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldResetPolicy, vs...))
}

// ResetAtEQ applies the EQ predicate on the "reset_at" field.
func ResetAtEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldResetAt, v))
}

// ResetAtNEQ applies the NEQ predicate on the "reset_at" field.
func ResetAtNEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldResetAt, v))
}

// ResetAtIn applies the In predicate on the "reset_at" field.
func ResetAtIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldResetAt, vs...))
}

// ResetAtNotIn applies the NotIn predicate on the "reset_at" field.
func ResetAtNotIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldResetAt, vs...))
}

// ResetAtGT applies the GT predicate on the "reset_at" field.
func ResetAtGT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldResetAt, v))
}

// ResetAtGTE applies the GTE predicate on the "reset_at" field.
func ResetAtGTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldResetAt, v))
}

// ResetAtLT applies the LT predicate on the "reset_at" field.
func ResetAtLT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldResetAt, v))
}

// ResetAtLTE applies the LTE predicate on the "reset_at" field.
func ResetAtLTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldResetAt, v))
}

// ResetAtIsNil applies the IsNil predicate on the "reset_at" field.
func ResetAtIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldResetAt))
}

// ResetAtNotNil applies the NotNil predicate on the "reset_at" field.
func ResetAtNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldResetAt))
}

// WindowStartedAtEQ applies the EQ predicate on the "window_started_at" field.
func WindowStartedAtEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldWindowStartedAt, v))
}

// WindowStartedAtNEQ applies the NEQ predicate on the "window_started_at" field.
func WindowStartedAtNEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldWindowStartedAt, v))
}

// WindowStartedAtIn applies the In predicate on the "window_started_at" field.
func WindowStartedAtIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldWindowStartedAt, vs...))
}

// WindowStartedAtNotIn applies the NotIn predicate on the "window_started_at" field.
func WindowStartedAtNotIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldWindowStartedAt, vs...))
}

// WindowStartedAtGT applies the GT predicate on the "window_started_at" field.
func WindowStartedAtGT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldWindowStartedAt, v))
}

// WindowStartedAtGTE applies the GTE predicate on the "window_started_at" field.
func WindowStartedAtGTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldWindowStartedAt, v))
}

// WindowStartedAtLT applies the LT predicate on the "window_started_at" field.
func WindowStartedAtLT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldWindowStartedAt, v))
}

// WindowStartedAtLTE applies the LTE predicate on the "window_started_at" field.
func WindowStartedAtLTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldWindowStartedAt, v))
}

// WindowStartedAtIsNil applies the IsNil predicate on the "window_started_at" field.
func WindowStartedAtIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldWindowStartedAt))
}

// WindowStartedAtNotNil applies the NotNil predicate on the "window_started_at" field.
func WindowStartedAtNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldWindowStartedAt))
}

// OverLimitActionEQ applies the EQ predicate on the "over_limit_action" field.
func OverLimitActionEQ(v OverLimitAction) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldOverLimitAction, v))
}

// OverLimitActionNEQ applies the NEQ predicate on the "over_limit_action" field.
func OverLimitActionNEQ(v OverLimitAction) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldOverLimitAction, v))
}

// OverLimitActionIn applies the In predicate on the "over_limit_action" field.
func OverLimitActionIn(vs ...OverLimitAction) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldOverLimitAction, vs...))
}

// OverLimitActionNotIn applies the NotIn predicate on the "over_limit_action" field.
func OverLimitActionNotIn(vs ...OverLimitAction) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldOverLimitAction, vs...))
}

// PauseUntilEQ applies the EQ predicate on the "pause_until" field.
func PauseUntilEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldPauseUntil, v))
}

// PauseUntilNEQ applies the NEQ predicate on the "pause_until" field.
func PauseUntilNEQ(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldPauseUntil, v))
}

// PauseUntilIn applies the In predicate on the "pause_until" field.
func PauseUntilIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldPauseUntil, vs...))
}

// PauseUntilNotIn applies the NotIn predicate on the "pause_until" field.
func PauseUntilNotIn(vs ...time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldPauseUntil, vs...))
}

// PauseUntilGT applies the GT predicate on the "pause_until" field.
func PauseUntilGT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldPauseUntil, v))
}

// PauseUntilGTE applies the GTE predicate on the "pause_until" field.
func PauseUntilGTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldPauseUntil, v))
}

// PauseUntilLT applies the LT predicate on the "pause_until" field.
func PauseUntilLT(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldPauseUntil, v))
}

// PauseUntilLTE applies the LTE predicate on the "pause_until" field.
func PauseUntilLTE(v time.Time) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldPauseUntil, v))
}

// PauseUntilIsNil applies the IsNil predicate on the "pause_until" field.
func PauseUntilIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldPauseUntil))
}

// PauseUntilNotNil applies the NotNil predicate on the "pause_until" field.
func PauseUntilNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldPauseUntil))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldSource, vs...))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContainsFold(FieldLastError, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.FieldContainsFold(FieldRemark, v))
}

// HasCredentials applies the HasEdge predicate on the "credentials" edge.
func HasCredentials() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CredentialsTable, CredentialsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCredentialsWith applies the HasEdge predicate on the "credentials" edge with a given conditions (other predicates).
func HasCredentialsWith(preds ...predicate.UpstreamCredential) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(func(s *sql.Selector) {
		step := newCredentialsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExecutions applies the HasEdge predicate on the "executions" edge.
func HasExecutions() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExecutionsTable, ExecutionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExecutionsWith applies the HasEdge predicate on the "executions" edge with a given conditions (other predicates).
func HasExecutionsWith(preds ...predicate.RequestExecution) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(func(s *sql.Selector) {
		step := newExecutionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CredentialQuotaScope) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CredentialQuotaScope) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CredentialQuotaScope) predicate.CredentialQuotaScope {
	return predicate.CredentialQuotaScope(sql.NotPredicates(p))
}
